{ pkgs, ... }:

{
  networking.firewall.allowedTCPPorts = [ 22 ];
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = true;
  };

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  users.users = {
    admin = {
      isNormalUser = true;
      extraGroups = [ "wheel" ];
      password = "admin";
    };
  };

  services.mysql = {
    enable = true;
    package = pkgs.mariadb;

    initialScript = pkgs.writeText "mysql-inital.sql" ''
      CREATE USER 'acore'@'127.0.0.1' IDENTIFIED BY 'foobar';
      FLUSH PRIVILEGES;
    '';

    ensureUsers = [
      {
        name = "acore";
        ensurePermissions = {
          "acore_auth.*" = "ALL PRIVILEGES";
          "acore_characters.*" = "ALL PRIVILEGES";
          "acore_world.*" = "ALL PRIVILEGES";
        };
      }
    ];
    ensureDatabases = [
      "acore_auth"
      "acore_characters"
      "acore_world"
    ];
  };

  systemd.services.azerothcore-wotlk-auth.requires = [ "mysql.service" ];
  systemd.services.azerothcore-wotlk-world.requires = [ "mysql.service" ];

  environment.systemPackages = with pkgs; [
    inetutils
    vim
  ];

  services.azerothcore-wotlk = {
    enable = true;

    auth = {
      db = {
        host = "127.0.0.1";
        port = 3306;
        username = "acore";
        password = "foobar";
        database = "acore_auth";
      };

      config = ''
        MaxPingTime = 30
        RealmServerPort = 3724
        EnableProxyProtocol = 0
        PidFile = ""
        UseProcessors = 0
        ProcessPriority = 0
        RealmsStateUpdateDelay = 20
        WrongPass.MaxCount = 0
        WrongPass.BanTime = 600
        WrongPass.BanType = 0
        WrongPass.Logging = 0
        BanExpiryCheckInterval = 60
        StrictVersionCheck = 0
        IPLocationFile = ""
        AllowLoggingIPAddressesInDatabase = 1
        Database.Reconnect.Seconds = 15
        Database.Reconnect.Attempts = 20
        LoginDatabase.WorkerThreads = 1
        LoginDatabase.SynchThreads = 1
        EnableTOTP =
        TOTPMasterSecret = ""
        Updates.EnableDatabases = 1
        Updates.AutoSetup = 1
        Updates.Redundancy = 1
        Updates.ArchivedRedundancy = 0
        Updates.AllowRehash = 1
        Updates.CleanDeadRefMaxCount = 3
        Appender.Console = 1,5,0,"1 9 3 6 5 8
        Appender.Auth = 2,5,0,Auth.log,w
        Logger.root = 4,Console Auth
      '';
    };

    world = {
      db = {
        host = "127.0.0.1";
        port = 3306;
        username = "acore";
        password = "foobar";
        characterDatabase = "acore_characters";
        worldDatabase = "acore_world";
      };

      config = ''
        RealmID = 1
        WorldServerPort = 8085
        LoginDatabase.WorkerThreads = 1
        WorldDatabase.WorkerThreads = 1
        CharacterDatabase.WorkerThreads = 1
        LoginDatabase.SynchThreads = 1
        WorldDatabase.SynchThreads = 1
        CharacterDatabase.SynchThreads = 1
        MaxPingTime = 30;
        Database.Reconnect.Seconds = 15
        Database.Reconnect.Attempts = 20
        PidFile = ""
        Console.Enable = 0
        BeepAtStart = 0
        FlashAtStart = 0
        Updates.EnableDatabases = 7
        Updates.AutoSetup = 1
        Updates.Redundancy = 1
        Updates.ArchivedRedundancy = 0
        Updates.AllowRehash = 1
        Updates.CleanDeadRefMaxCount = 3
        Network.Threads = 1
        Network.OutKBuff = -1
        Network.OutUBuff = 4096
        Network.TcpNodelay = 1
        Network.EnableProxyProtocol = 0
        Ra.Enable = 1
        Ra.IP = "0.0.0.0"
        Ra.Port = 3443
        Ra.MinLevel = 3
        SOAP.Enabled = 1
        SOAP.IP = "127.0.0.1"
        SOAP.Port = 7878
        TOTPMasterSecret = ""
        ThreadPool = 2
        UseProcessors = 0
        ProcessPriority = 1
        Compression = 1
        PacketLogFile = ""
        LogDB.Opt.ClearInterval = 10
        LogDB.Opt.ClearTime = 1209600
        RecordUpdateTimeDiffInterval = 300000
        MinRecordUpdateTimeDiff = 100
        IPLocationFile = ""
        AllowLoggingIPAddressesInDatabase = 1
        Allow.IP.Based.Action.Logging = 0
        Appender.Console = 1,4,0,"1 9 3 6 5 8
        Appender.Server = "2,5,0,Server.log,w"
        Appender.Errors = "2,5,0,Errors.log"
        Logger.root = "2,Console Server"
        Logger.diff = "3,Console Server"
        Logger.mmaps = "4,Server"
        Logger.scripts.hotswap = "4,Console Server"
        Logger.server = "4,Console Server"
        Logger.sql.sql = "2,Console Errors"
        Logger.sql="4,Console Server"
        Logger.time.update = "4,Console Server"
        Logger.module = "4,Console Server"
        Logger.spells.scripts = "2,Console Errors"
        Log.Async.Enable = 0
        Metric.Enable = 0
        Metric.Interval = 1
        Metric.ConnectionInfo = "127.0.0.18086worldserver"
        Metric.OverallStatusInterval = 1
        BirthdayTime = 1222964635
        PlayerLimit = 1000
        World.RealmAvailability = 1
        GameType = 0
        RealmZone = 1
        DBC.Locale = 255
        Expansion = 2
        ClientCacheVersion = 0
        SessionAddDelay = 10000
        CloseIdleConnections = 1
        SocketTimeOutTime = 900000
        SocketTimeOutTimeActive = 60000
        MaxOverspeedPings = 2
        DisconnectToleranceInterval = 0
        EnableLoginAfterDC = 1
        MinWorldUpdateTime = 1
        UpdateUptimeInterval = 1
        MaxCoreStuckTime = 0
        SaveRespawnTimeImmediately = 1
        Server.LoginInfo = 0
        ShowKickInWorld = 0
        ShowMuteInWorld = 0
        ShowBanInWorld = 0
        MaxWhoListReturns = 49
        PreventAFKLogout = 0
        PacketSpoof.Policy = 1
        PacketSpoof.BanMode = 0
        PacketSpoof.BanDuration = 86400
        Warden.Enabled = 1
        Warden.NumMemChecks = 3
        Warden.NumLuaChecks = 1
        Warden.NumOtherChecks = 7
        Warden.ClientResponseDelay = 600
        Warden.ClientCheckHoldOff = 30
        Warden.ClientCheckFailAction = 0
        Warden.BanDuration = 259200
        AutoBroadcast.On = 0
        AutoBroadcast.Center = 0
        AutoBroadcast.Timer = 60000
        AutoBroadcast.MinDisableLevel = 0
        Visibility.GroupMode = 1
        Visibility.Distance.Continents = 90
        Visibility.Distance.Instances = 120
        Visibility.Distance.BGArenas = 180
        Visibility.Notify.Period.OnContinents = 1000
        Visibility.Notify.Period.InInstances = 1000
        Visibility.Notify.Period.InBGArenas = 1000
        Visibility.ObjectSparkles = 1
        Visibility.ObjectQuestMarkers = 1
        MapUpdateInterval = 10
        MapUpdate.Threads = 1
        MoveMaps.Enable = 1
        vmap.enableLOS = 1
        vmap.enableHeight = 1
        vmap.petLOS = 1
        vmap.BlizzlikePvPLOS = 1
        vmap.BlizzlikeLOSInOpenWorld = 1
        vmap.enableIndoorCheck = 1
        DetectPosCollision = 1
        CheckGameObjectLoS = 1
        PreloadAllNonInstancedMapGrids = 0
        SetAllCreaturesWithWaypointMovementActive = 0
        DontCacheRandomMovementPaths = 0
        ActivateWeather = 1
        ChangeWeatherInterval = 600000
        AllowTickets = 1
        LevelReq.Ticket = 1
        DeletedCharacterTicketTrace = 0
        AllowPlayerCommands = 1
        Command.LookupMaxResults = 0
        Die.Command.Mode = 1
        GM.LoginState = 2
        GM.Visible = 2
        GM.Chat = 2
        GM.WhisperingTo = 2
        GM.InGMList.Level = 3
        GM.InWhoList.Level = 3
        GM.StartLevel = 1
        GM.AllowInvite = 1
        GM.AllowFriend = 1
        GM.LowerSecurity = 0
        GM.TicketSystem.ChanceOfGMSurvey = 50
        DisableWaterBreath = 4
        AllFlightPaths = 1
        InstantFlightPaths = 1
        AlwaysMaxSkillForLevel = 1
        AlwaysMaxWeaponSkill = 1
        PlayerStart.AllReputation = 0
        PlayerStart.CustomSpells = 0
        PlayerStart.MapsExplored = 1
        InstantLogout = 1
        CastUnstuck = 1
        PlayerSaveInterval = 900000
        PlayerSave.Stats.MinLevel = 0
        PlayerSave.Stats.SaveOnlyOnLogout = 1
        CleanCharacterDB = 0
        PersistentCharacterCleanFlags = 0
        CharDelete.Method = 1
        CharDelete.MinLevel = 0
        CharDelete.KeepDays = 30
        MinPlayerName = 3
        MinPetName = 3
        DeclinedNames = 1
        StrictNames.Reserved = 1
        StrictNames.Profanity = 1
        StrictPlayerNames = 1
        StrictPetNames = 1
        CharacterCreating.Disabled = 0
        CharacterCreating.Disabled.RaceMask = 0
        CharacterCreating.Disabled.ClassMask = 0
        CharactersPerAccount = 50
        CharactersPerRealm = 10
        HeroicCharactersPerRealm = 1
        CharacterCreating.MinLevelForHeroicCharacter = 0
        StartPlayerLevel = 1
        StartHeroicPlayerLevel = 55
        SkipCinematics = 0
        StartPlayerMoney = 10000
        StartHeroicPlayerMoney = 200000
        PlayerStart.String = ""
        EnablePlayerSettings = 0
        MaxPlayerLevel = 80
        MinDualSpecLevel = 40
        WaterBreath.Timer = 180000
        EnableLowLevelRegenBoost = 1
        Rate.MoveSpeed = 1
        Rate.Damage.Fall = 1
        Rate.Talent = 1
        Rate.Talent.Pet = 1
        Rate.Health = 1
        Rate.Mana = 1
        Rate.Rage.Income = 1
        Rate.Rage.Loss = 1
        Rate.RunicPower.Income = 1
        Rate.RunicPower.Loss = 1
        Rate.Focus = 1
        Rate.Energy = 1
        Rate.Loyalty = 1
        Rate.Rest.InGame = 1
        Rate.Rest.Offline.InTavernOrCity = 5
        Rate.Rest.Offline.InWilderness = 1
        Rate.MissChanceMultiplier.TargetCreature = 11
        Rate.MissChanceMultiplier.TargetPlayer = 7
        Rate.MissChanceMultiplier.OnlyAffectsPlayer = 0
        LevelReq.Trade = 1
        NoResetTalentsCost = 1
        ToggleXP.Cost = 100000
        MaxPrimaryTradeSkill = 5
        SkillChance.Prospecting = 1
        SkillChance.Milling = 1
        Rate.Skill.Discovery = 1
        SkillGain.Crafting = 1
        SkillGain.Defense = 1
        SkillGain.Gathering = 1
        SkillGain.Weapon = 1
        SkillChance.Orange = 100
        SkillChance.Yellow = 75
        SkillChance.Green = 25
        SkillChance.Grey = 10
        SkillChance.MiningSteps = 0
        SkillChance.SkinningSteps = 0
        OffhandCheckAtSpellUnlearn = 1
        Stats.Limits.Enable = 0
        Stats.Limits.Dodge = 95.0
        Stats.Limits.Parry = 95.0
        Stats.Limits.Block = 95.0
        Stats.Limits.Crit = 95.0
        Rate.Reputation.Gain = 5
        Rate.Reputation.LowLevel.Kill = 1
        Rate.Reputation.LowLevel.Quest = 1
        Rate.Reputation.RecruitAFriendBonus = 0.1
        MaxGroupXPDistance = 84
        Rate.XP.Kill = 3
        Rate.XP.Quest = 3
        Rate.XP.Quest.DF = 3
        Rate.XP.Explore = 3
        Rate.XP.Pet = 3
        Rate.XP.BattlegroundKillAV = 1
        Rate.XP.BattlegroundKillWSG = 1
        Rate.XP.BattlegroundKillAB = 1
        Rate.XP.BattlegroundKillEOTS = 1
        Rate.XP.BattlegroundKillSOTA = 1
        Rate.XP.BattlegroundKillIC = 1
        Rate.Pet.LevelXP = 5.0e-2
        MaxHonorPoints = 75000
        MaxHonorPointsMoneyPerPoint = 0
        StartHonorPoints = 0
        HonorPointsAfterDuel = 0
        Rate.Honor = 1
        MaxArenaPoints = 10000
        StartArenaPoints = 0
        Arena.LegacyArenaPoints = 0
        Rate.ArenaPoints = 1
        PvPToken.Enable = 0
        PvPToken.MapAllowType = 4
        PvPToken.ItemID = 29434
        PvPToken.ItemCount = 1
        DurabilityLoss.InPvP = 0
        DurabilityLoss.OnDeath = 10
        DurabilityLossChance.Damage = 0.5
        DurabilityLossChance.Absorb = 0.5
        DurabilityLossChance.Parry = 5.0e-2
        DurabilityLossChance.Block = 5.0e-2
        Death.SicknessLevel = 81
        Death.CorpseReclaimDelay.PvP = 1
        Death.CorpseReclaimDelay.PvE = 0
        Death.Bones.World = 1
        Death.Bones.BattlegroundOrArena = 1
        Pet.RankMod.Health = 1
        ItemDelete.Method = 0
        ItemDelete.Vendor = 0
        ItemDelete.Quality = 3
        ItemDelete.ItemLevel = 80
        DBC.EnforceItemAttributes = 1
        Rate.Drop.Item.Poor = 1
        Rate.Drop.Item.Normal = 1
        Rate.Drop.Item.Uncommon = 1
        Rate.Drop.Item.Rare = 1
        Rate.Drop.Item.Epic = 1
        Rate.Drop.Item.Legendary = 1
        Rate.Drop.Item.Artifact = 1
        Rate.Drop.Item.Referenced = 1
        Rate.Drop.Money = 1
        Rate.Drop.Item.ReferencedAmount = 1
        Rate.Drop.Item.GroupAmount = 1
        LootNeedBeforeGreedILvlRestriction = 70
        Item.SetItemTradeable = 1
        Quests.EnableQuestTracker = 0
        QuestPOI.Enabled = 1
        Quests.LowLevelHideDiff = 4
        Quests.HighLevelHideDiff = 7
        Quests.IgnoreRaid = 0
        Quests.IgnoreAutoAccept = 0
        Quests.IgnoreAutoComplete = 0
        Rate.RewardQuestMoney = 1
        Rate.RewardBonusMoney = 1
        MonsterSight = 50.0
        Rate.Creature.Aggro = 1
        CreatureFamilyFleeAssistanceRadius = 30
        CreatureFamilyAssistanceRadius = 10
        CreatureFamilyAssistanceDelay = 2000
        CreatureFamilyAssistancePeriod = 3000
        CreatureFamilyFleeDelay = 7000
        WorldBossLevelDiff = 3
        Corpse.Decay.NORMAL = 60
        Corpse.Decay.RARE = 300
        Corpse.Decay.ELITE = 300
        Corpse.Decay.RAREELITE = 300
        Corpse.Decay.WORLDBOSS = 3600
        Rate.Corpse.Decay.Looted = 0.5
        Rate.Creature.Normal.Damage = 1
        Rate.Creature.Elite.Elite.Damage = 1
        Rate.Creature.Elite.RARE.Damage = 1
        Rate.Creature.Elite.RAREELITE.Damage = 1
        Rate.Creature.Elite.WORLDBOSS.Damage = 1
        Rate.Creature.Normal.SpellDamage = 1
        Rate.Creature.Elite.Elite.SpellDamage = 1
        Rate.Creature.Elite.RARE.SpellDamage = 1
        Rate.Creature.Elite.RAREELITE.SpellDamage = 1
        Rate.Creature.Elite.WORLDBOSS.SpellDamage = 1
        Rate.Creature.Normal.HP = 1
        Rate.Creature.Elite.Elite.HP = 1
        Rate.Creature.Elite.RARE.HP = 1
        Rate.Creature.Elite.RAREELITE.HP = 1
        Rate.Creature.Elite.WORLDBOSS.HP = 1
        ListenRange.Say = 40
        ListenRange.TextEmote = 40
        ListenRange.Yell = 300
        Creature.MovingStopTimeForPlayer = 180000
        WaypointMovementStopTimeForPlayer = 120
        NpcEvadeIfTargetIsUnreachable = 5
        NpcRegenHPIfTargetIsUnreachable = 1
        NpcRegenHPTimeIfTargetIsUnreachable = 10
        Creatures.CustomIDs = "190010,55005,999991,25462,98888,601014,34567,34568"
        Rate.SellValue.Item.Poor = 1
        Rate.SellValue.Item.Normal = 1
        Rate.SellValue.Item.Uncommon = 1
        Rate.SellValue.Item.Rare = 1
        Rate.SellValue.Item.Epic = 1
        Rate.SellValue.Item.Legendary = 1
        Rate.SellValue.Item.Artifact = 1
        Rate.SellValue.Item.Heirloom = 1
        Rate.BuyValue.Item.Poor = 1
        Rate.BuyValue.Item.Normal = 1
        Rate.BuyValue.Item.Uncommon = 1
        Rate.BuyValue.Item.Rare = 1
        Rate.BuyValue.Item.Epic = 1
        Rate.BuyValue.Item.Legendary = 1
        Rate.BuyValue.Item.Artifact = 1
        Rate.BuyValue.Item.Heirloom = 1
        Rate.RepairCost = 1
        LeaveGroupOnLogout.Enabled = 0
        Group.Raid.LevelRestriction = 10
        Instance.GMSummonPlayer = 1
        Instance.IgnoreLevel = 1
        Instance.IgnoreRaid = 1
        Instance.ResetTimeHour = 4
        Instance.ResetTimeRelativeTimestamp = 1135814400
        Rate.InstanceResetTime = 1
        Instance.UnloadDelay = 1800000
        AccountInstancesPerHour = 10
        Instance.SharedNormalHeroicId = 1
        DungeonAccessRequirements.PrintMode = 1
        DungeonAccessRequirements.PortalAvgIlevelCheck = 0
        DungeonAccessRequirements.OptionalStringID = 0
        JoinBGAndLFG.Enable = 0
        DungeonFinder.OptionsMask = 5
        LFG.Location.All = 0
        LFG.MaxKickCount = 2
        LFG.KickPreventionTimer = 900
        DungeonAccessRequirements.LFGLevelDBCOverride = 0
        MinCharterName = 2
        StrictCharterNames = 1
        Guild.EventLogRecordsCount = 100
        Guild.ResetHour = 6
        Guild.BankEventLogRecordsCount = 25
        MinPetitionSigns = 9
        Guild.CharterCost = 1000
        Guild.AllowMultipleGuildMaster = 1
        Guild.BankInitialTabs = 6
        Guild.BankTabCost0 = 1000000
        Guild.BankTabCost1 = 2500000
        Guild.BankTabCost2 = 5000000
        Guild.BankTabCost3 = 10000000
        Guild.BankTabCost4 = 25000000
        Guild.BankTabCost5 = 50000000
        Guild.MemberLimit = 0
        FFAPvPTimer = 30
        Wintergrasp.Enable = 1
        Wintergrasp.PlayerMax = 120
        Wintergrasp.PlayerMin = 0
        Wintergrasp.PlayerMinLvl = 77
        Wintergrasp.BattleTimer = 30
        Wintergrasp.NoBattleTimer = 150
        Wintergrasp.CrashRestartTimer = 10
        Battleground.CastDeserter = 1
        Battleground.QueueAnnouncer.Enable = 0
        Battleground.QueueAnnouncer.Limit.MinLevel = 0
        Battleground.QueueAnnouncer.Limit.MinPlayers = 3
        Battleground.QueueAnnouncer.SpamProtection.Delay = 30
        Battleground.QueueAnnouncer.PlayerOnly = 0
        Battleground.QueueAnnouncer.Timed = 0
        Battleground.QueueAnnouncer.Timer = 30000
        Battleground.PrematureFinishTimer = 300000
        Battleground.PremadeGroupWaitForMatch = 1800000
        Battleground.GiveXPForKills = 0
        Battleground.Random.ResetHour = 6
        Battleground.StoreStatistics.Enable = 1
        Battleground.TrackDeserters.Enable = 1
        Battleground.InvitationType = 0
        Battleground.ReportAFK.Timer = 4
        Battleground.ReportAFK = 3
        Battleground.DisableQuestShareInBG = 0
        Battleground.DisableReadyCheckInBG = 0
        Battleground.RewardWinnerHonorFirst = 30
        Battleground.RewardWinnerArenaFirst = 25
        Battleground.RewardWinnerHonorLast = 15
        Battleground.RewardWinnerArenaLast = 0
        Battleground.RewardLoserHonorFirst = 5
        Battleground.RewardLoserHonorLast = 5
        Battleground.PlayerRespawn = 30
        Battleground.RestorationBuffRespawn = 20
        Battleground.BerserkingBuffRespawn = 120
        Battleground.SpeedBuffRespawn = 150
        Arena.MaxRatingDifference = 150
        Arena.RatingDiscardTimer = 600000
        Arena.PreviousOpponentsDiscardTimer = 120000
        Arena.AutoDistributePoints = 0
        Arena.AutoDistributeInterval = 7
        Arena.GamesRequired = 10
        Arena.QueueAnnouncer.Enable = 0
        Arena.QueueAnnouncer.PlayerOnly = 0
        Arena.QueueAnnouncer.Detail = 3
        Arena.ArenaSeason.ID = 8
        Arena.ArenaSeason.InProgress = 1
        Arena.ArenaStartRating = 0
        Arena.ArenaStartPersonalRating = 0
        Arena.ArenaStartMatchmakerRating = 1500
        Arena.ArenaWinRatingModifier1 = 48
        Arena.ArenaWinRatingModifier2 = 24
        Arena.ArenaLoseRatingModifier = 24
        Arena.ArenaMatchmakerRatingModifier = 24
        ArenaTeam.CharterCost.2v2= 800000
        ArenaTeam.CharterCost.3v3 = 1200000
        ArenaTeam.CharterCost.5v5 = 2000000
        MaxAllowedMMRDrop = 500
        MailDeliveryDelay = 10
        LevelReq.Mail = 1
        IsContinentTransport.Enabled = 1
        IsPreloadedContinentTransport.Enabled = 0
        StrictChannelNames = 1
        AddonChannel = 1
        ChatFakeMessagePreventing = 1
        ChatStrictLinkChecking.Severity = 0
        ChatStrictLinkChecking.Kick = 0
        ChatFlood.MessageCount = 10
        ChatFlood.MessageDelay = 1
        ChatFlood.AddonMessageCount = 100
        ChatFlood.AddonMessageDelay = 1
        ChatFlood.MuteTime = 10
        Chat.MuteFirstLogin = 0
        Chat.MuteTimeFirstLogin = 120
        Channel.RestrictedLfg = 1
        Channel.SilentlyGMJoin = 0
        Channel.ModerationGMLevel = 1
        ChatLevelReq.Channel = 1
        ChatLevelReq.Whisper = 1
        ChatLevelReq.Say = 1
        PartyLevelReq = 1
        PreserveCustomChannels = 1
        PreserveCustomChannelDuration = 14
        AllowTwoSide.Accounts = 1
        AllowTwoSide.Interaction.Calendar = 1
        AllowTwoSide.Interaction.Chat = 1
        AllowTwoSide.Interaction.Emote = 1
        AllowTwoSide.Interaction.Channel = 1
        AllowTwoSide.Interaction.Group = 1
        AllowTwoSide.Interaction.Guild = 1
        AllowTwoSide.Interaction.Arena = 1
        AllowTwoSide.Interaction.Auction = 1
        AllowTwoSide.Interaction.Mail = 1
        AllowTwoSide.WhoList = 1
        AllowTwoSide.AddFriend = 1
        AllowTwoSide.Trade = 1
        TalentsInspecting = 1
        ChangeFaction.MaxMoney = 0
        RecruitAFriend.MaxLevel = 6
        RecruitAFriend.MaxDifference = 4
        MaxRecruitAFriendBonusDistance = 100
        Calendar.DeleteOldEventsHour = 6
        Event.Announce = 0
        AuctionHouse.SearchTimeout = 1000
        LevelReq.Auction = 10
        Rate.Auction.Time = 1
        Rate.Auction.Deposit = 1
        Rate.Auction.Cut = 1
        PlayerDump.DisallowPaths = 1
        PlayerDump.DisallowOverwrite = 1
        ICC.Buff.Horde = 73822
        ICC.Buff.Alliance = 73828
        Minigob.Manabonk.Enable = 1
        Calculate.Creature.Zone.Area.Data = 0
        Calculate.Gameoject.Zone.Area.Data = 0
        TeleportTimeoutNear = 25
        TeleportTimeoutFar = 45
        DailyRBGArenaPoints.MinLevel = 71
        Debug.Battleground = 0
        Debug.Arena = 0
      '';
    };
  };

  virtualisation.vmVariant = {
    # following configuration is added only when building VM with build-vm
    virtualisation = {
      memorySize = 4096; # Use 4GB memory.
      diskSize = 20480; # 20GB of root diskspace
      cores = 4;
      graphics = false;
      forwardPorts = [
        {
          from = "host";
          host.port = 2222;
          guest.port = 22;
        }
        {
          from = "host";
          host.port = 3724;
          guest.port = 3724;
        }
        {
          from = "host";
          host.port = 8084;
          guest.port = 8084;
        }
      ];
    };
  };

  security.sudo.wheelNeedsPassword = false;

  system.stateVersion = "24.05";
}
