INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81000, 'Sanctified Scourgelord Pauldrons', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81001, 'Sanctified Scourgelord Legguards', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81002, 'Sanctified Scourgelord Faceguard', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81003, 'Sanctified Scourgelord Handguards', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81004, 'Sanctified Scourgelord Chestguard', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81005, 'Sanctified Scourgelord Battleplate', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81006, 'Sanctified Scourgelord Gauntlets', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81007, 'Sanctified Scourgelord Helmet', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81008, 'Sanctified Scourgelord Legplates', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81009, 'Sanctified Scourgelord Shoulderplates', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81010, 'Sanctified Lasherweave Robes', 20);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81011, 'Sanctified Lasherweave Gauntlets', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81012, 'Sanctified Lasherweave Helmet', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81013, 'Sanctified Lasherweave Legplates', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81014, 'Sanctified Lasherweave Pauldrons', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81015, 'Sanctified Lasherweave Shoulderpads', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81016, 'Sanctified Lasherweave Legguards', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81017, 'Sanctified Lasherweave Headguard', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81018, 'Sanctified Lasherweave Handgrips', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81019, 'Sanctified Lasherweave Raiment', 20);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81020, 'Sanctified Lasherweave Mantle', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81021, 'Sanctified Lasherweave Trousers', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81022, 'Sanctified Lasherweave Cover', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81023, 'Sanctified Lasherweave Gloves', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81024, 'Sanctified Lasherweave Vestment', 20);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81025, 'Sanctified Ahn\'Kahar Blood Hunter\'s Handguards', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81026, 'Sanctified Ahn\'Kahar Blood Hunter\'s Headpiece', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81027, 'Sanctified Ahn\'Kahar Blood Hunter\'s Legguards', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81028, 'Sanctified Ahn\'Kahar Blood Hunter\'s Spaulders', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81029, 'Sanctified Ahn\'Kahar Blood Hunter\'s Tunic', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81030, 'Sanctified Bloodmage Gloves', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81031, 'Sanctified Bloodmage Hood', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81032, 'Sanctified Bloodmage Leggings', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81033, 'Sanctified Bloodmage Robe', 20);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81034, 'Sanctified Bloodmage Shoulderpads', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81035, 'Sanctified Lightsworn Shoulderplates', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81036, 'Sanctified Lightsworn Legplates', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81037, 'Sanctified Lightsworn Helmet', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81038, 'Sanctified Lightsworn Gauntlets', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81039, 'Sanctified Lightsworn Battleplate', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81040, 'Sanctified Lightsworn Shoulderguards', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81041, 'Sanctified Lightsworn Legguards', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81042, 'Sanctified Lightsworn Handguards', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81043, 'Sanctified Lightsworn Faceguard', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81044, 'Sanctified Lightsworn Chestguard', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81045, 'Sanctified Lightsworn Spaulders', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81046, 'Sanctified Lightsworn Tunic', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81047, 'Sanctified Lightsworn Headpiece', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81048, 'Sanctified Lightsworn Greaves', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81049, 'Sanctified Lightsworn Gloves', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81050, 'Sanctified Crimson Acolyte Pants', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81051, 'Sanctified Crimson Acolyte Raiments', 20);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81052, 'Sanctified Crimson Acolyte Mantle', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81053, 'Sanctified Crimson Acolyte Handwraps', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81054, 'Sanctified Crimson Acolyte Cowl', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81055, 'Sanctified Crimson Acolyte Gloves', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81056, 'Sanctified Crimson Acolyte Hood', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81057, 'Sanctified Crimson Acolyte Leggings', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81058, 'Sanctified Crimson Acolyte Robe', 20);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81059, 'Sanctified Crimson Acolyte Shoulderpads', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81060, 'Sanctified Shadowblade Breastplate', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81061, 'Sanctified Shadowblade Gauntlets', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81062, 'Sanctified Shadowblade Helmet', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81063, 'Sanctified Shadowblade Legplates', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81064, 'Sanctified Shadowblade Pauldrons', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81065, 'Sanctified Frost Witch\'s Shoulderguards', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81066, 'Sanctified Frost Witch\'s War-Kilt', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81067, 'Sanctified Frost Witch\'s Faceguard', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81068, 'Sanctified Frost Witch\'s Grips', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81069, 'Sanctified Frost Witch\'s Chestguard', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81070, 'Sanctified Frost Witch\'s Spaulders', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81071, 'Sanctified Frost Witch\'s Legguards', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81072, 'Sanctified Frost Witch\'s Headpiece', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81073, 'Sanctified Frost Witch\'s Handguards', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81074, 'Sanctified Frost Witch\'s Tunic', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81075, 'Sanctified Frost Witch\'s Shoulderpads', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81076, 'Sanctified Frost Witch\'s Kilt', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81077, 'Sanctified Frost Witch\'s Helm', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81078, 'Sanctified Frost Witch\'s Gloves', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81079, 'Sanctified Frost Witch\'s Hauberk', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81080, 'Sanctified Dark Coven Gloves', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81081, 'Sanctified Dark Coven Hood', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81082, 'Sanctified Dark Coven Leggings', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81083, 'Sanctified Dark Coven Robe', 20);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81084, 'Sanctified Dark Coven Shoulderpads', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81085, 'Sanctified Ymirjar Lord\'s Battleplate', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81086, 'Sanctified Ymirjar Lord\'s Gauntlets', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81087, 'Sanctified Ymirjar Lord\'s Helmet', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81088, 'Sanctified Ymirjar Lord\'s Legplates', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81089, 'Sanctified Ymirjar Lord\'s Shoulderplates', 3);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81090, 'Sanctified Ymirjar Lord\'s Breastplate', 5);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81091, 'Sanctified Ymirjar Lord\'s Greathelm', 1);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81092, 'Sanctified Ymirjar Lord\'s Handguards', 10);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81093, 'Sanctified Ymirjar Lord\'s Legguards', 7);
INSERT INTO `item_set_names` (`entry`, `NAME`, `InventoryType`) VALUES (81094, 'Sanctified Ymirjar Lord\'s Pauldrons', 3);
