name: Crash / Server Crash issues
description: Did your server crash? Post an issue here!
title: "Crash: "
labels: ["Priority-Critical", "HasBacktrace"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report. Remember to fill out all fields including the title above. 
        An issue that is not properly filled out will be closed.
  - type: textarea
    id: current
    attributes:
      label: Steps to Reproduce
      description: |
        If possible provide detailed steps to reproduce the crash.
      placeholder: |
        1. Provide the exact steps to trigger the crash.
        2. Include any relevant configurations or commands.
        3. Mention if the crash is consistent or intermittent.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        NOTE: Make sure your server was compiled in RelWithDebug or Debug mode as crashlogs from Release do not contain enough information.
  - type: textarea
    id: logs
    attributes:
      label: Logs and Screenshots
      description: |
        Do you have any logs or screenshots that can be useful?
        Crash logs in text are preffered over screenshots.
        If you have logs in text form please upload them to [Gist](https://gist.github.com/) or PasteBin and upload the link.
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating System
      description: |
        The Operating System you are having issues on.
        i.e. Windows 11 x64, Debian 10 x64, macOS 12, Ubuntu 20.04
    validations:
      required: true
  - type: textarea
    id: deps
    attributes:
      label: Dependencies & versions
      description: |
        Relevant information about dependencies and their versions that can be useful to debug the issue.
        Example:
        - OpenSSL ver ...
        - Boost ver ...
        - MySQL ver ...
        - Visual Studio ver ...
        - GCC ver ...
        - Clang ver ...
        - CMake ver ... 
    validations:
      required: true
  - type: input
    id: commit
    attributes:
      label: Commit
      description: |
        Which commit hash are you using.
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: |
        Do you have any other relevant information about the issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution.
        If you use AzerothCore regularly, we really NEED your help to:
        - Test our fixes: https://www.azerothcore.org/wiki/How-to-test-a-PR
        - Report issues or suggestions: https://github.com/azerothcore/azerothcore-wotlk/issues/new/choose
        - Improve the documentation/wiki: https://www.azerothcore.org/wiki/home
        With your help, the project can evolve much quicker!
