/*
 * This file is part of the AzerothCore Project. See AUTHORS file for Copyright information
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef ACORE_AREA_DEFINES_H
#define ACORE_AREA_DEFINES_H

#include "Define.h"

enum AreaTableIDs : uint32
{
    AREA_DUN_MOROGH                                          = 1,
    AREA_BADLANDS                                            = 3,
    AREA_BLASTED_LANDS                                       = 4,
    AREA_SWAMP_OF_SORROWS                                    = 8,
    AREA_DUSKWOOD                                            = 10,
    AREA_WETLANDS                                            = 11,
    AREA_ELWYNN_FOREST                                       = 12,
    AREA_DUROTAR                                             = 14,
    AREA_DUSTWALLOW_MARSH                                    = 15,
    AREA_AZSHARA                                             = 16,
    AREA_THE_BARRENS                                         = 17,
    AREA_WESTERN_PLAGUELANDS                                 = 28,
    AREA_STRANGLETHORN_VALE                                  = 33,
    AREA_LOCH_MODAN                                          = 38,
    AREA_WESTFALL                                            = 40,
    AREA_REDRIDGE_MOUNTAINS                                  = 44,
    AREA_ARATHI_HIGHLANDS                                    = 45,
    AREA_BURNING_STEPPES                                     = 46,
    AREA_THE_HINTERLANDS                                     = 47,
    AREA_SEARING_GORGE                                       = 51,
    AREA_DRAGONBLIGHT                                        = 65,
    AREA_ZUL_DRAK                                            = 66,
    AREA_THE_STORM_PEAKS                                     = 67,
    AREA_TIRISFAL_GLADES                                     = 85,
    AREA_GOLDSHIRE                                           = 87,
    AREA_WESTFALL_LIGHTHOUSE                                 = 115,
    AREA_SILVERPINE_FOREST                                   = 130,
    AREA_KHARANOS                                            = 131,
    AREA_EASTERN_PLAGUELANDS                                 = 139,
    AREA_TELDRASSIL                                          = 141,
    AREA_DARKSHORE                                           = 148,
    AREA_BRILL                                               = 159,
    AREA_FELSTONE_FIELD                                      = 199,
    AREA_DALSONS_TEARS                                       = 200,
    AREA_GAHRRONS_WITHERING                                  = 201,
    AREA_THE_WRITHING_HAUNT                                  = 202,
    AREA_MULGORE                                             = 215,
    AREA_HILLSBRAD_FOOTHILLS                                 = 267,
    AREA_ASHENVALE                                           = 331,
    AREA_FERALAS                                             = 357,
    AREA_RAZOR_HILL                                          = 362,
    AREA_CAMP_TAURAJO                                        = 378,
    AREA_THE_CROSSROADS                                      = 380,
    AREA_THE_MERCHANT_COAST                                  = 391,
    AREA_GRIZZLY_HILLS                                       = 394,
    AREA_THOUSAND_NEEDLES                                    = 400,
    AREA_DESOLACE                                            = 405,
    AREA_STONETALON_MOUNTAINS                                = 406,
    AREA_TANARIS                                             = 440,
    AREA_MOONGLADE                                           = 493,
    AREA_HOWLING_FJORD                                       = 495,
    AREA_WINTERSPRING                                        = 618,
    AREA_GATES_OF_IRONFORGE                                  = 809,
    AREA_ROCKTUSK_FARM                                       = 1296,
    AREA_SILITHUS                                            = 1377,
    AREA_UNDERCITY                                           = 1497,
    AREA_STORMWIND_CITY                                      = 1519,
    AREA_IRONFORGE                                           = 1537,
    AREA_ORGRIMMAR                                           = 1637,
    AREA_THUNDER_BLUFF                                       = 1638,
    AREA_DARNASSUS                                           = 1657,
    AREA_STRATHOLME                                          = 2017,
    AREA_SCHOLOMANCE                                         = 2057,
    AREA_ALCAZ_ISLAND                                        = 2079,
    AREA_DEEPRUN_TRAM                                        = 2257,
    AREA_ALTERAC_VALLEY                                      = 2597,
    AREA_CRYSTALSONG_FOREST                                  = 2817,
    AREA_WARSONG_GULCH                                       = 3277,
    AREA_ARATHI_BASIN                                        = 3358,
    AREA_AHN_QIRAJ                                           = 3428,
    AREA_RUINS_OF_AHN_QIRAJ                                  = 3429,
    AREA_EVERSONG_WOODS                                      = 3430,
    AREA_GHOSTLANDS                                          = 3433,
    AREA_HELLFIRE_PENINSULA                                  = 3483,
    AREA_SILVERMOON_CITY                                     = 3487,
    AREA_NAGRAND                                             = 3518,
    AREA_TEROKKAR_FOREST                                     = 3519,
    AREA_SHADOWMOON_VALLEY                                   = 3520,
    AREA_ZANGARMARSH                                         = 3521,
    AREA_BLADES_EDGE_MOUNTAINS                               = 3522,
    AREA_NETHERSTORM                                         = 3523,
    AREA_AZUREMYST_ISLE                                      = 3524,
    AREA_BLOODMYST_ISLE                                      = 3525,
    AREA_BOREAN_TUNDRA                                       = 3537,
    AREA_THE_EXODAR                                          = 3557,
    AREA_HELLFIRE_RAMPARTS                                   = 3562,
    AREA_HELLFIRE_CITADEL                                    = 3563,
    AREA_AZURE_WATCH                                         = 3576,
    AREA_SERPENTSHRINE_CAVERN                                = 3607,
    AREA_HALAA                                               = 3628,
    AREA_FALCONWING_SQUARE                                   = 3665,
    AREA_NAGRAND_ARENA                                       = 3698,
    AREA_BLADES_EDGE_ARENA                                   = 3702,
    AREA_SHATTRATH_CITY                                      = 3703,
    AREA_NORDRASSIL                                          = 3710,
    AREA_SHOLAZAR_BASIN                                      = 3711,
    AREA_THE_BLOOD_FURNACE                                   = 3713,
    AREA_THE_SHATTERED_HALLS                                 = 3714,
    AREA_THE_STEAMVAULT                                      = 3715,
    AREA_THE_UNDERBOG                                        = 3716,
    AREA_THE_SLAVE_PENS                                      = 3717,
    AREA_SOCRETHARS_SEAT                                     = 3742,
    AREA_SHADOW_LABYRINTH                                    = 3789,
    AREA_AUCHENAI_CRYPTS                                     = 3790,
    AREA_SETHEKK_HALLS                                       = 3791,
    AREA_MANA_TOMBS                                          = 3792,
    AREA_EYE_OF_THE_STORM                                    = 3820,
    AREA_MAGTHERIDONS_LAIR                                   = 3836,
    AREA_THE_BOTANICA                                        = 3847,
    AREA_THE_ARCATRAZ                                        = 3848,
    AREA_THE_MECHANAR                                        = 3849,
    AREA_INVASION_POINT_OVERLORD                             = 3900,
    AREA_RUINS_OF_LORDAERON                                  = 3968,
    AREA_SHATTERED_STRAITS                                   = 4064,
    AREA_SUNWELL_PLATEAU                                     = 4075,
    AREA_ISLE_OF_QUEL_DANAS                                  = 4080,
    AREA_THE_CULLING_OF_STRATHOLME                           = 4100,
    AREA_NAXXANAR                                            = 4128,
    AREA_MAGISTERS_TERRACE                                   = 4131,
    AREA_WINTERGARDE_KEEP                                    = 4177,
    AREA_WINTERGRASP                                         = 4197,
    AREA_THE_OCULUS                                          = 4228,
    AREA_ULDUAR                                              = 4273,
    AREA_PLAGUELANDS_THE_SCARLET_ENCLAVE                     = 4298,
    AREA_DALARAN_ARENA                                       = 4378,
    AREA_STRAND_OF_THE_ANCIENTS                              = 4384,
    AREA_DALARAN                                             = 4395,
    ARENA_THE_RING_OF_VALOR                                  = 4406,
    AREA_THE_VIOLET_HOLD                                     = 4415,
    AREA_VALLEY_OF_ANCIENT_WINTERS                           = 4437,
    AREA_THE_SUNKEN_RING                                     = 4538,
    AREA_THE_BROKEN_TEMPLE                                   = 4539,
    AREA_SEWER_EXIT_PIPE                                     = 4569,
    AREA_WINTERGRASP_FORTRESS                                = 4575,
    AREA_THE_CHILLED_QUAGMIRE                                = 4589,
    AREA_WESTSPARK_WORKSHOP                                  = 4611,
    AREA_EASTSPARK_WORKSHOP                                  = 4612,
    AREA_VARGOTHS_RETREAT                                    = 4637,
    AREA_FORMATION_GROUNDS                                   = 4652,
    AREA_THE_CONSERVATORY_OF_LIFE                            = 4656,
    AREA_ARGENT_TOURNAMENT_GROUNDS                           = 4658,
    AREA_THE_RING_OF_CHAMPIONS                               = 4669,
    AREA_THE_ASPIRANTS_RING                                  = 4670,
    AREA_THE_ARGENT_VALIANTS_RING                            = 4671,
    AREA_THE_ALLIANCE_VALIANTS_RING                          = 4672,
    AREA_THE_HORDE_VALIANTS_RING                             = 4673,
    AREA_SUNREAVER_PAVILION                                  = 4676,
    AREA_SILVER_COVENANT_PAVILION                            = 4677,
    AREA_ISLE_OF_CONQUEST                                    = 4710,
    AREA_ICECROWN_CITADEL                                    = 4812,
    AREA_HALLS_OF_REFLECTION                                 = 4820,
    AREA_THE_FROZEN_THRONE                                   = 4859,
    AREA_THE_FROST_QUEENS_LAIR                               = 4889,
    AREA_PUTRICIDES_LABORATORY_OF_ALCHEMICAL_HORRORS_AND_FUN = 4890,
    AREA_THE_SANCTUM_OF_BLOOD                                = 4891,
    AREA_FROSTMOURNE                                         = 4910,
    AREA_THE_RUBY_SANCTUM                                    = 4987
};

enum MapIDs : uint32
{
    MAP_EASTERN_KINGDOMS                     = 0,
    MAP_KALIMDOR                             = 1,
    MAP_SCOTT_TEST                           = 25,
    MAP_ALTERAC_VALLEY                       = 30,
    MAP_SHADOWFANG_KEEP                      = 33,
    MAP_STORMWIND_STOCKADE                   = 34,
    MAP_DEADMINES                            = 36,
    MAP_WAILING_CAVERNS                      = 43,
    MAP_RAZORFEN_KRAUL                       = 47,
    MAP_BLACKFATHOM_DEEPS                    = 48,
    MAP_ULDAMAN                              = 70,
    MAP_GNOMEREGAN                           = 90,
    MAP_SUNKEN_TEMPLE                        = 109,
    MAP_RAZORFEN_DOWNS                       = 129,
    MAP_SCARLET_MONASTERY                    = 189,
    MAP_ZUL_FARRAK                           = 209,
    MAP_BLACKROCK_SPIRE                      = 229,
    MAP_BLACKROCK_DEPTHS                     = 230,
    MAP_ONYXIAS_LAIR                         = 249,
    MAP_OPENING_OF_THE_DARK_PORTAL           = 269,
    MAP_SCHOLOMANCE                          = 289,
    MAP_ZUL_GURUB                            = 309,
    MAP_STRATHOLME                           = 329,
    MAP_MARAUDON                             = 349,
    MAP_RAGEFIRE_CHASM                       = 389,
    MAP_MOLTEN_CORE                          = 409,
    MAP_DIRE_MAUL                            = 429,
    MAP_BLACKWING_LAIR                       = 469,
    MAP_WARSONG_GULCH                        = 489,
    MAP_RUINS_OF_AHN_QIRAJ                   = 509,
    MAP_ARATHI_BASIN                         = 529,
    MAP_OUTLAND                              = 530,
    MAP_AHN_QIRAJ_TEMPLE                     = 531,
    MAP_KARAZHAN                             = 532,
    MAP_NAXXRAMAS                            = 533,
    MAP_THE_BATTLE_FOR_MOUNT_HYJAL           = 534,
    MAP_HELLFIRE_CITADEL_THE_SHATTERED_HALLS = 540,
    MAP_HELLFIRE_CITADEL_THE_BLOOD_FURNACE   = 542,
    MAP_HELLFIRE_CITADEL_RAMPARTS            = 543,
    MAP_MAGTHERIDONS_LAIR                    = 544,
    MAP_COILFANG_THE_STEAMVAULT              = 545,
    MAP_COILFANG_THE_UNDERBOG                = 546,
    MAP_COILFANG_THE_SLAVE_PENS              = 547,
    MAP_COILFANG_SERPENTSHRINE_CAVERN        = 548,
    MAP_TEMPEST_KEEP                         = 550,
    MAP_TEMPEST_KEEP_THE_ARCATRAZ            = 552,
    MAP_TEMPEST_KEEP_THE_BOTANICA            = 553,
    MAP_TEMPEST_KEEP_THE_MECHANAR            = 554,
    MAP_AUCHINDOUN_SHADOW_LABYRINTH          = 555,
    MAP_AUCHINDOUN_SETHEKK_HALLS             = 556,
    MAP_AUCHINDOUN_MANA_TOMBS                = 557,
    MAP_AUCHINDOUN_AUCHENAI_CRYPTS           = 558,
    MAP_THE_ESCAPE_FROM_DURNHOLDE            = 560,
    MAP_BLACK_TEMPLE                         = 564,
    MAP_GRUULS_LAIR                          = 565,
    MAP_EYE_OF_THE_STORM                     = 566,
    MAP_ZUL_AMAN                             = 568,
    MAP_NORTHREND                            = 571,
    MAP_UTGARDE_KEEP                         = 574,
    MAP_UTGARDE_PINNACLE                     = 575,
    MAP_THE_NEXUS                            = 576,
    MAP_THE_OCULUS                           = 578,
    MAP_THE_SUNWELL                          = 580,
    MAP_MAGISTERS_TERRACE                    = 585,
    MAP_THE_CULLING_OF_STRATHOLME            = 595,
    MAP_HALLS_OF_STONE                       = 599,
    MAP_DRAK_THARON_KEEP                     = 600,
    MAP_AZJOL_NERUB                          = 601,
    MAP_HALLS_OF_LIGHTNING                   = 602,
    MAP_ULDUAR                               = 603,
    MAP_GUNDRAK                              = 604,
    MAP_STRAND_OF_THE_ANCIENTS               = 607,
    MAP_VIOLET_HOLD                          = 608,
    MAP_EBON_HOLD                            = 609,
    MAP_THE_OBSIDIAN_SANCTUM                 = 615,
    MAP_THE_EYE_OF_ETERNITY                  = 616,
    MAP_THE_RING_OF_VALOR                    = 618,
    MAP_AHN_KAHET_THE_OLD_KINGDOM            = 619,
    MAP_VAULT_OF_ARCHAVON                    = 624,
    MAP_ISLE_OF_CONQUEST                     = 628,
    MAP_ICECROWN_CITADEL                     = 631,
    MAP_THE_FORGE_OF_SOULS                   = 632,
    MAP_TRIAL_OF_THE_CRUSADER                = 649,
    MAP_TRIAL_OF_THE_CHAMPION                = 650,
    MAP_PIT_OF_SARON                         = 658,
    MAP_HALLS_OF_REFLECTION                  = 668,
    MAP_THE_RUBY_SANCTUM                     = 724
};

#endif
