## SHORTHAND FOR CMAKE_INSTALL_PREFIX
if( INSTALL_PATH )
  set(CMAKE_INSTALL_PREFIX "${INSTALL_PATH}")
endif()

## BIN PATH
set(AUTHSERVER_PATH "${CMAKE_INSTALL_PREFIX}/${AUTHSERVER_DIR}")
set(WORLDSERVER_PATH "${CMAKE_INSTALL_PREFIX}/${WORLDSERVER_DIR}")

## CONF PATH
set(AUTHSERVER_CONF_PATH "${AUTHSERVER_PATH}")
set(WORLDSERVER_CONF_PATH "${WORLDSERVER_PATH}")

## MODULES CONFIGURATION
if( NOT MODULES_CONF_DIR )
  set(MODULES_CONF_DIR "modules_conf")
  message(STATUS "Using default module configuration directory.")
endif()
set(MODULES_CONF_PATH "${WORLDSERVER_PATH}/${MODULES_CONF_DIR}")
## COMPATIBILITY WITH BADLY CODED (AND OLD) MODULES
set(CONF_DIR "${MODULES_CONF_PATH}")
