## FALLBACK FOR "PREFIX" OPTION WHICH IS DEPRECATED NOW & SHOULD BE DELETED IN THE FUTURE
if( PREFIX )
  set(INSTALL_PATH "${PREFIX}")
endif()

## SHORTHAND FOR CMAKE_INSTALL_PREFIX
if( INSTALL_PATH )
  set(CMAKE_INSTALL_PREFIX "${INSTALL_PATH}")
endif()

## BIN PATH
if ( SERVER_BIN_PATH )
    set(AUTHSERVER_BIN_PATH "${AUTHSERVER_BIN_PATH}")
    set(WORLDSERVER_BIN_PATH "${AUTHSERVER_BIN_PATH}")
endif()
if ( SERVER_BIN_DIR )
    set(AUTHSERVER_BIN_PATH "${CMAKE_INSTALL_PREFIX}/${SERVER_BIN_DIR}")
    set(WORLDSERVER_BIN_PATH "${CMAKE_INSTALL_PREFIX}/${SERVER_BIN_DIR}")
else()
    set(AUTHSERVER_BIN_PATH "${CMAKE_INSTALL_PREFIX}/${AUTHSERVER_BIN_DIR}")
    set(WORLDSERVER_BIN_PATH "${CMAKE_INSTALL_PREFIX}/${WORLDSERVER_BIN_DIR}")
endif()


## CONF PATH
if ( SERVER_CONF_PATH )
    set(AUTHSERVER_CONF_PATH "${SERVER_CONF_PATH}")
    set(WORLDSERVER_CONF_PATH "${SERVER_CONF_PATH}")
else()
    set(AUTHSERVER_CONF_PATH "${AUTHSERVER_BIN_PATH}")
    set(WORLDSERVER_CONF_PATH "${WORLDSERVER_BIN_PATH}")
endif()

## MODULES CONFIGURATION
if( NOT MODULES_CONF_DIR )
  set(MODULES_CONF_DIR "modules_conf")
  message(STATUS "Using default module configuration directory.")
endif()
## DEFAULT PATH FOR MODULES CONF CAN BE OVERRIDEN
if( NOT MODULES_CONF_PATH )
    set(MODULES_CONF_PATH "${WORLDSERVER_BIN_PATH}/${MODULES_CONF_DIR}")
endif()
## COMPATIBILITY WITH BADLY CODED (AND OLD) MODULES
set(CONF_DIR "${MODULES_CONF_PATH}")
