#!/usr/bin/env python3
"""Dump custom-range item_template rows to definitions/item.json.

The other custom DBC rows are deterministic and generated by
`definitions/_generate.py`. Items are not - they are hand-curated in the
SQL migration `2026_05_22_00_blackrose_data.sql`. To keep `Item.dbc` in
the client patch in sync with the server's `item_template`, this script
reads the live `acore_world.item_template` table and writes the matching
DBC fields out as JSON.

Without an Item.dbc entry on the client, the WoW 3.3.5a client cannot
classify the item locally and breaks right-click behavior for any
equippable custom item (trinkets, bags) - it sends the wrong opcode
which the server rejects with EQUIP_ERR_ITEM_NOT_FOUND.

Re-run after editing item rows in the SQL migration:

    python3 tools/clientpatch/dump_items.py

Then re-run `build_patch.py merge` to repack the patch.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


HERE = Path(__file__).parent
DEFAULT_OUT = HERE / "definitions" / "item.json"

CUSTOM_RANGE_LOW = 900100
CUSTOM_RANGE_HIGH = 900999

# Item.dbc field order. Maps to item_template columns one-to-one.
DBC_COLUMNS = [
    "ID", "ClassID", "SubclassID", "SoundOverrideSubclassID",
    "Material", "DisplayInfoID", "InventoryType", "SheatheType",
]

SQL_QUERY = """\
SELECT
    entry                   AS ID,
    class                   AS ClassID,
    subclass                AS SubclassID,
    SoundOverrideSubclass   AS SoundOverrideSubclassID,
    Material                AS Material,
    displayid               AS DisplayInfoID,
    InventoryType           AS InventoryType,
    sheath                  AS SheatheType
FROM `item_template`
WHERE entry BETWEEN {lo} AND {hi}
ORDER BY entry;
"""


def run_mysql(query: str, *, host: str, user: str, password: str,
              database: str) -> str:
    """Run a query via the `mysql` CLI and return its stdout (TSV)."""
    if not shutil.which("mysql"):
        sys.exit("ERROR: `mysql` CLI not found in PATH")
    cmd = [
        "mysql", "-h", host, "-u", user, f"-p{password}",
        "--batch", "--raw",
        "-e", query, database,
    ]
    result = subprocess.run(
        cmd, check=False, capture_output=True, text=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        sys.exit(f"ERROR: mysql exited {result.returncode}")
    return result.stdout


def parse_tsv(stdout: str) -> list[dict[str, int]]:
    lines = [ln for ln in stdout.splitlines() if ln.strip()]
    if not lines:
        return []
    header = lines[0].split("\t")
    if header != DBC_COLUMNS:
        sys.exit(
            f"ERROR: column header mismatch. expected {DBC_COLUMNS},"
            f" got {header}"
        )
    rows: list[dict[str, int]] = []
    for raw in lines[1:]:
        parts = raw.split("\t")
        if len(parts) != len(header):
            sys.exit(f"ERROR: malformed row: {raw!r}")
        row = {col: int(val) for col, val in zip(header, parts)}
        rows.append(row)
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default=os.environ.get("MYSQL_HOST", "127.0.0.1"))
    parser.add_argument("--user", default=os.environ.get("MYSQL_USER", "acore"))
    parser.add_argument("--password", default=os.environ.get("MYSQL_PASSWORD", "acore"))
    parser.add_argument("--database", default=os.environ.get("MYSQL_DB", "acore_world"))
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--low", type=int, default=CUSTOM_RANGE_LOW)
    parser.add_argument("--high", type=int, default=CUSTOM_RANGE_HIGH)
    args = parser.parse_args()

    query = SQL_QUERY.format(lo=args.low, hi=args.high)
    stdout = run_mysql(
        query,
        host=args.host, user=args.user,
        password=args.password, database=args.database,
    )
    rows = parse_tsv(stdout)
    if not rows:
        sys.exit(
            f"ERROR: no item_template rows in [{args.low},{args.high}]."
            " Did the world DB import run yet?"
        )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(rows, indent=2) + "\n")
    print(f"Wrote {len(rows)} item rows -> {args.out.relative_to(HERE.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
