"""Emit a single ``rev_*.sql`` for an authored invasion project.

The output targets ``data/sql/updates/pending_db_world/`` and is built to pass
``apps/codestyle/codestyle-sql.py``:

* every ``INSERT`` sits directly under a matching ``DELETE`` (no blank line between),
* all identifiers are backticked, numeric values are bare,
* ``branding_event_spawn`` is created ``IF NOT EXISTS`` with the InnoDB engine,
* 4-space conventions: LF lines, no tabs, no trailing whitespace, no double blank lines, final
  newline, single blank line between logical blocks.

A *block* is a list of consecutive lines with no internal blank lines; blocks are joined by exactly
one blank line, which keeps ``DELETE``/``INSERT`` pairs adjacent while separating sections.
"""

from __future__ import annotations

from ..guid import GuidAllocator
from ..model import Invasion, Project, Spawn

# creature.guid is supplied; every other column falls back to its schema default.
_CREATURE_COLS = (
    "guid", "id1", "map", "zoneId", "spawnMask", "phaseMask",
    "position_x", "position_y", "position_z", "orientation", "spawntimesecs", "MovementType",
)
_WAYPOINT_COLS = ("id", "point", "position_x", "position_y", "position_z", "orientation", "delay", "move_type")
_ADDON_COLS = ("guid", "path_id")
_FORMATION_COLS = ("leaderGUID", "memberGUID", "dist", "angle", "groupAI")
_GROUP_TEMPLATE_COLS = ("groupId", "groupName", "groupFlags")
_GROUP_COLS = ("groupId", "spawnType", "spawnId")
_EVENT_SPAWN_COLS = ("zone_id", "event_type", "group_id", "map_id")

# AzerothCore SpawnGroupFlags / SpawnObjectType.
_SPAWNGROUP_FLAG_MANUAL_SPAWN = 4  # members do not auto-spawn on grid load; the scheduler drives them
_SPAWN_TYPE_CREATURE = 0


def emit_sql(project: Project, allocator: GuidAllocator) -> str:
    """Render the whole project to one SQL document string."""
    if not project.invasions:
        raise ValueError("project has no invasions to export")

    blocks: list[list[str]] = []
    blocks.append(
        [
            "-- Generated by the mod-branding invasion authoring tool.",
            "-- Ambient invasion content (design §9.1): event defs, spawns, paths, formations.",
        ]
    )
    blocks.append(_create_event_spawn_table())
    for inv in project.invasions:
        blocks.extend(_invasion_blocks(inv, allocator))

    lines: list[str] = []
    for i, block in enumerate(blocks):
        if i:
            lines.append("")
        lines.extend(block)
    return "\n".join(lines).rstrip("\n") + "\n"


def _fmt(value: object) -> str:
    if isinstance(value, bool):
        return str(int(value))
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return repr(float(value))  # shortest round-trip; no scientific notation in our coordinate ranges


def _insert(table: str, columns: tuple[str, ...], rows: list[tuple]) -> list[str]:
    cols = ", ".join(f"`{c}`" for c in columns)
    out = [f"INSERT INTO `{table}` ({cols}) VALUES"]
    last = len(rows) - 1
    for i, row in enumerate(rows):
        term = ";" if i == last else ","
        out.append("(" + ", ".join(_fmt(v) for v in row) + ")" + term)
    return out


def _delete_in(table: str, column: str, ids: list[int]) -> str:
    joined = ", ".join(str(i) for i in ids)
    return f"DELETE FROM `{table}` WHERE `{column}` IN ({joined});"


def _delete_event(table: str, zone_id: int, event_type: int) -> str:
    return f"DELETE FROM `{table}` WHERE `zone_id` = {zone_id} AND `event_type` = {event_type};"


def _create_event_spawn_table() -> list[str]:
    return [
        "-- branding_event_spawn (design §9.1): links an event (zone, type) to the manual spawn_group",
        "-- the tool authored, so EventScheduler drives SpawnGroupSpawn/Despawn on the map on cycle.",
        "CREATE TABLE IF NOT EXISTS `branding_event_spawn`",
        "(",
        "    `zone_id` INT UNSIGNED NOT NULL,",
        "    `event_type` TINYINT UNSIGNED NOT NULL COMMENT '0=Invasion,1=Surge,2=EliteHunt,3=ProfAnomaly',",
        "    `group_id` INT UNSIGNED NOT NULL COMMENT 'spawn_group_template.groupId (manual-spawn group)',",
        "    `map_id` SMALLINT UNSIGNED NOT NULL COMMENT 'map the group lives on',",
        "    PRIMARY KEY (`zone_id`, `event_type`)",
        ") ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;",
    ]


def _invasion_blocks(inv: Invasion, allocator: GuidAllocator) -> list[list[str]]:
    zone = inv.event.zone_id
    etype = int(inv.event.event_type)

    # Allocate one creature GUID per spawn (in order), one path id per non-empty path, one spawn
    # group id for the whole invasion.
    guids = allocator.allocate_guids(len(inv.spawns))
    guid_of = {s.local_id: g for s, g in zip(inv.spawns, guids, strict=True)}
    path_id_of = {p.local_id: allocator.allocate_path_id() for p in inv.paths if p.waypoints}
    group_id = allocator.allocate_group_id()

    blocks: list[list[str]] = []

    # branding_event_def
    blocks.append(
        [
            f"-- {inv.name} (zone {zone}, type {etype})",
            _delete_event("branding_event_def", zone, etype),
            *_insert(
                "branding_event_def",
                ("zone_id", "event_type", "goal", "active_seconds", "cooldown_seconds"),
                [(zone, etype, inv.event.goal, inv.event.active_seconds, inv.event.cooldown_seconds)],
            ),
        ]
    )

    # creature
    creature_rows = [
        (
            guid_of[s.local_id], s.template_id, inv.map_id, zone, 1, 1,
            s.x, s.y, s.z, s.orientation, s.spawntimesecs, s.movement_type,
        )
        for s in inv.spawns
    ]
    blocks.append(
        [
            "-- invasion creature spawns",
            _delete_in("creature", "guid", list(guids)),
            *_insert("creature", _CREATURE_COLS, creature_rows),
        ]
    )

    # waypoint_data (paths with at least one point)
    wp_paths = [p for p in inv.paths if p.waypoints]
    if wp_paths:
        wp_rows = [
            (path_id_of[p.local_id], point, w.x, w.y, w.z, w.orientation, w.delay_ms, w.move_type)
            for p in wp_paths
            for point, w in enumerate(p.waypoints, start=1)
        ]
        blocks.append(
            [
                "-- waypoint paths",
                _delete_in("waypoint_data", "id", [path_id_of[p.local_id] for p in wp_paths]),
                *_insert("waypoint_data", _WAYPOINT_COLS, wp_rows),
            ]
        )

    # creature_addon (link path-followers to their waypoint path)
    addon_spawns: list[Spawn] = [s for s in inv.spawns if s.path_local_id in path_id_of]
    if addon_spawns:
        addon_rows = [(guid_of[s.local_id], path_id_of[s.path_local_id]) for s in addon_spawns]
        blocks.append(
            [
                "-- path links",
                _delete_in("creature_addon", "guid", [guid_of[s.local_id] for s in addon_spawns]),
                *_insert("creature_addon", _ADDON_COLS, addon_rows),
            ]
        )

    # creature_formations (leader self-row + members)
    if inv.formations:
        formation_rows: list[tuple] = []
        leader_guids: list[int] = []
        for f in inv.formations:
            leader = guid_of[f.leader_local_id]
            leader_guids.append(leader)
            formation_rows.append((leader, leader, 0.0, 0.0, f.group_ai))
            for member_local in f.member_local_ids:
                formation_rows.append((leader, guid_of[member_local], f.follow_dist, f.follow_angle, f.group_ai))
        blocks.append(
            [
                "-- formations",
                _delete_in("creature_formations", "leaderGUID", leader_guids),
                *_insert("creature_formations", _FORMATION_COLS, formation_rows),
            ]
        )

    # spawn_group_template (a manual-spawn group so the creatures never auto-appear on grid load)
    group_name = f"branding inv z{zone} t{etype}"[:100]
    blocks.append(
        [
            "-- manual spawn group (driven by EventScheduler)",
            _delete_in("spawn_group_template", "groupId", [group_id]),
            *_insert(
                "spawn_group_template",
                _GROUP_TEMPLATE_COLS,
                [(group_id, group_name, _SPAWNGROUP_FLAG_MANUAL_SPAWN)],
            ),
        ]
    )

    # spawn_group (group membership: every authored creature)
    blocks.append(
        [
            "-- spawn group membership",
            _delete_in("spawn_group", "groupId", [group_id]),
            *_insert(
                "spawn_group",
                _GROUP_COLS,
                [(group_id, _SPAWN_TYPE_CREATURE, guid_of[s.local_id]) for s in inv.spawns],
            ),
        ]
    )

    # branding_event_spawn mapping (event -> group + map)
    blocks.append(
        [
            "-- event -> spawn group mapping",
            _delete_event("branding_event_spawn", zone, etype),
            *_insert(
                "branding_event_spawn",
                _EVENT_SPAWN_COLS,
                [(zone, etype, group_id, inv.map_id)],
            ),
        ]
    )

    return blocks
