#include "ace/XML_Svc_Conf.h"

#if (ACE_USES_CLASSIC_SVC_CONF == 0)

ACE_BEGIN_VERSIONED_NAMESPACE_DECL

ACE_XML_Svc_Conf::~ACE_XML_Svc_Conf (void)
{
}

ACE_END_VERSIONED_NAMESPACE_DECL

#endif /* ACE_USES_CLASSIC_SVC_CONF == 0 */
