#ifndef SHAREDDEFINES_H
#define SHAREDDEFINES_H

// enum AzthRbac {
//     RBAC_PERM_COMMAND_QUESTCOMPLETER = 1000,
//     RBAC_PERM_COMMAND_AZTH = 1001,
//     RBAC_PERM_COMMAND_AZTH_MAXSKILL = 1002,
//     RBAC_PERM_COMMAND_AZTH_XP = 1003,
//     RBAC_PERM_PVP_CUSTOM = 1004 // Arena Spectator ADDON commands
// };

#endif /* SHAREDDEFINES_H */

