"""Emit the AzerothCore world SQL for the craft catalog.

One generated rev file carries the whole closed loop:

* ``item_template`` -- resources (#27), Branded outputs (#27), recipe pattern items (#29);
* ``branding_recipe`` -- the #09 loader mirror, repointed off the placeholder cloth onto the real
  Branded outputs (#27);
* ``spell_dbc`` -- the native CREATE_ITEM craft spells injected into the server DBC store (#29);
* ``skilllineability_dbc`` -- maps each craft spell into its profession skill line (#29).

The ``spell_dbc`` / ``skilllineability_dbc`` tables are AzerothCore's SQL overrides of Spell.dbc /
SkillLineAbility.dbc (``DBCStores.cpp`` ``LoadFromDB``); the client gets the matching rows from the
generated Spell.dbc patch (see :mod:`branding_craft.emit_dbc`) so client and server agree.

Output obeys ``apps/codestyle/codestyle-sql.py``: 4-space indent, every INSERT preceded by its
matching DELETE, InnoDB, single trailing newline.
"""

from __future__ import annotations

from . import constants as C
from .catalog import CATALOG, Catalog
from .validate import assert_valid


def _values_row(values: list) -> str:
    cells = []
    for v in values:
        if isinstance(v, str):
            cells.append("'" + v.replace("'", "''") + "'")
        else:
            cells.append(str(v))
    return "    (" + ", ".join(cells) + ")"


def _insert(table: str, columns: list[str], rows: list[list], delete_where: str) -> str:
    # The DELETE must sit on the line immediately above the INSERT (codestyle-sql.py).
    out = [f"DELETE FROM `{table}` WHERE {delete_where};"]
    cols = ", ".join(f"`{c}`" for c in columns)
    out.append(f"INSERT INTO `{table}` ({cols}) VALUES")
    body = [_values_row(r) for r in rows]
    out.append(",\n".join(body) + ";")
    return "\n".join(out)


def _item_template_block(cat: Catalog) -> str:
    # Explicit column list -- only the fields a resource / armour / recipe entry needs; everything
    # else takes the item_template defaults.
    columns = [
        "entry", "class", "subclass", "name", "displayid", "Quality", "BuyPrice", "SellPrice",
        "InventoryType", "ItemLevel", "RequiredLevel", "RequiredSkill", "RequiredSkillRank",
        "stackable", "stat_type1", "stat_value1", "stat_type2", "stat_value2", "armor",
        "spellid_1", "spelltrigger_1", "bonding", "Material",
    ]

    rows: list[list] = []
    entries: list[int] = []

    # Resources (trade goods). Material 4 == cloth sound/material; harmless flavour. The generic
    # Material/Fragment plus one per-school Fragment for every BrandId (the "Fire-Branded Fragment"
    # loop) -- all share the resource emit shape; only bind/quality/name differ.
    for res in (cat.material, cat.fragment, *cat.school_fragments):
        entries.append(res.entry)
        rows.append([
            res.entry, res.item_class, res.subclass, res.name, res.displayid, res.quality,
            0, 1, 0, 0, 0, 0, 0, res.stackable, 0, 0, 0, 0, 0, 0, 0, res.bonding, 4,
        ])

    # Branded outputs (armour, modest stats -- power comes from branding procs, §1/§27).
    for out in cat.outputs:
        entries.append(out.entry)
        rows.append([
            out.entry, out.item_class, out.subclass, out.name, out.displayid, out.quality,
            0, 100, out.inventory_type, out.item_level, 0, out.required_skill, out.required_skill_rank,
            1, 7, 12, 5, 8, 250, 0, 0, C.BIND_TO_ACCOUNT, 4,
        ])

    # Recipe pattern items (BoP) that teach the craft spell on use.
    for r in cat.recipes:
        entries.append(r.pattern_entry)
        rows.append([
            r.pattern_entry, C.ITEM_CLASS_RECIPE, r.pattern_subclass, f"Pattern: {r.name}",
            r.pattern_displayid, r.pattern_quality, 0, 5000, 0, 0, 0, r.skill_line, r.req_skill_value,
            1, 0, 0, 0, 0, 0, r.spell_id, C.SPELL_TRIGGER_LEARN, C.BIND_WHEN_PICKED_UP, 0,
        ])

    where = "`entry` IN (" + ", ".join(str(e) for e in entries) + ")"
    return _insert("item_template", columns, rows, where)


def _branding_recipe_block(cat: Catalog) -> str:
    columns = ["id", "materials", "fragments", "output_item", "char_xp", "school"]
    rows = [
        [r.id, r.material_count, r.fragment_count, r.output.entry, r.char_xp, r.school]
        for r in cat.recipes
    ]
    ids = ", ".join(str(r.id) for r in cat.recipes)
    return _insert("branding_recipe", columns, rows, f"`id` IN ({ids})")


def emit_branding_recipe_sql(cat: Catalog = CATALOG) -> str:
    """Emit ONLY the branding_recipe mirror INSERT (the #27 repoint).

    branding_recipe is owned by the #09 loader's core pending rev (it CREATEs the table); this block
    repoints its output_item rows onto the real Branded outputs. Kept separate from the module's
    db-world file so the table has a single home, and so the values stay catalog-generated.
    """

    assert_valid(cat)
    header = (
        "-- branding_recipe mirror repointed onto the Branded outputs (#27 §8.6).\n"
        "-- GENERATED by tools/branding-craft (`branding-craft recipe-sql`) -- counts mirror the\n"
        "-- craft spells in modules/mod-branding/data/sql/db-world (the #29 lockstep)."
    )
    return header + "\n" + _branding_recipe_block(cat) + "\n"


def _spell_dbc_block(cat: Catalog) -> str:
    columns = [
        "ID", "Attributes", "CastingTimeIndex", "RangeIndex", "EquippedItemClass",
        "Reagent_1", "Reagent_2", "ReagentCount_1", "ReagentCount_2",
        "Effect_1", "EffectDieSides_1", "EffectBasePoints_1", "ImplicitTargetA_1", "EffectItemType_1",
        "Name_Lang_enUS",
    ]
    rows: list[list] = []
    for r in cat.recipes:
        reagents = cat.reagents(r)
        reagent_items = [0, 0]
        reagent_counts = [0, 0]
        for i, (item, count) in enumerate(reagents):
            reagent_items[i] = item
            reagent_counts[i] = count
        rows.append([
            r.spell_id, C.SPELL_ATTR0_IS_TRADESPELL, C.CAST_TIME_INDEX_INSTANT, C.RANGE_INDEX_SELF,
            C.EQUIPPED_ITEM_CLASS_NONE,
            reagent_items[0], reagent_items[1], reagent_counts[0], reagent_counts[1],
            C.SPELL_EFFECT_CREATE_ITEM, 1, 0, C.TARGET_UNIT_CASTER, r.output.entry,
            r.name,
        ])
    ids = ", ".join(str(r.spell_id) for r in cat.recipes)
    return _insert("spell_dbc", columns, rows, f"`ID` IN ({ids})")


def _skilllineability_dbc_block(cat: Catalog) -> str:
    columns = [
        "ID", "SkillLine", "Spell", "MinSkillLineRank",
        "TrivialSkillLineRankHigh", "TrivialSkillLineRankLow",
    ]
    rows = [
        [r.skill_line_ability_id, r.skill_line, r.spell_id, r.req_skill_value,
         r.trivial_high, r.req_skill_value]
        for r in cat.recipes
    ]
    ids = ", ".join(str(r.skill_line_ability_id) for r in cat.recipes)
    return _insert("skilllineability_dbc", columns, rows, f"`ID` IN ({ids})")


def emit_world_sql(cat: Catalog = CATALOG) -> str:
    """Return the full pending_db_world rev SQL for the catalog (generated -- do not hand-edit)."""

    assert_valid(cat)

    header = (
        "-- mod-branding native profession crafting (#27 server content + #29 craft spells).\n"
        "-- GENERATED by tools/branding-craft -- do not hand-edit; change src/branding_craft/catalog.py\n"
        "-- and re-run `branding-craft world-sql`. Reagent counts here share their source with the\n"
        "-- client Spell.dbc patch and the branding_recipe mirror, so the three cannot drift (#29).\n"
        "-- The branding_recipe mirror itself is repointed by `branding-craft recipe-sql` (it lives in\n"
        "-- the #09 loader's core pending rev, the table's single home)."
    )

    sections = [
        header,
        "-- #27 item_template: resources, Branded outputs, recipe patterns.",
        _item_template_block(cat),
        "-- #29 spell_dbc: native CREATE_ITEM craft spells (server DBC override).",
        _spell_dbc_block(cat),
        "-- #29 skilllineability_dbc: craft spell -> profession skill line.",
        _skilllineability_dbc_block(cat),
    ]
    return "\n\n".join(sections) + "\n"
