{
 "title": "Performance profiling",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "realm",
    "query": "show tag values from events with key = realm"
   }
  ]
 },
 "panels": [
  {
   "title": "Update diff",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Update diff",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "update_time_diff",
     "query": "SELECT max(\"value\") FROM \"update_time_diff\" WHERE (\"realm\" =~ /$realm$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/$realm$/" }
     ]
    }
   ]
  },
  {
   "title": "World Update - Split",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "world_update_time_total",
     "query": "SELECT max(\"value\") FROM \"map_update_time_diff\" WHERE (\"realm\" =~ /^$realm$/) AND $timeFilter GROUP BY time($__interval), \"map_id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/^$realm$/" }
     ]
    },
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "world_update_time",
     "query": "SELECT max(\"value\") FROM \"map_update_time_diff\" WHERE (\"realm\" =~ /^$realm$/) AND $timeFilter GROUP BY time($__interval), \"map_id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/^$realm$/" }
     ]
    }
   ]
  },
  {
   "title": "World Update - Stacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "world_update_time",
     "query": "SELECT max(\"value\") FROM \"map_update_time_diff\" WHERE (\"realm\" =~ /^$realm$/) AND $timeFilter GROUP BY time($__interval), \"map_id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/^$realm$/" },
      { "condition": "AND", "key": "parent_type", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Map update - Split",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Map $tag_map_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "map_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "map_update_time_diff",
     "query": "SELECT max(\"value\") FROM \"map_update_time_diff\" WHERE (\"realm\" =~ /^$realm$/) AND $timeFilter GROUP BY time($__interval), \"map_id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/^$realm$/" }
     ]
    }
   ]
  },
  {
   "title": "Map update - Stacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Map $tag_map_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "map_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "map_update_time_diff",
     "query": "SELECT max(\"value\") FROM \"map_update_time_diff\" WHERE (\"realm\" =~ /^$realm$/) AND $timeFilter GROUP BY time($__interval), \"map_id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/^$realm$/" }
     ]
    }
   ]
  },
  {
   "title": "Update sessions - Split",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Account ID $tag_account_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "account_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "world_update_sessions_time",
     "query": "SELECT max(\"value\") FROM \"map_update_time_diff\" WHERE (\"realm\" =~ /^$realm$/) AND $timeFilter GROUP BY time($__interval), \"map_id\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/^$realm$/" }
     ]
    }
   ]
  },
  {
   "title": "Opcode handlers - Split",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Opcode $tag_opcode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "opcode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worldsession_update_opcode_time",
     "query": "SELECT max(\"value\") FROM \"worldsession_update_opcode_time\" WHERE (\"realm\" =~ /^$realm$/) AND $timeFilter GROUP BY time($__interval), \"opcode\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/^$realm$/" }
     ]
    }
   ]
  },
  {
   "title": "Creatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Map $tag_map_id Instance $tag_map_instanceid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "map_id" ], "type": "tag" },
      { "params": [ "map_instanceid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "map_creatures",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/^$realm$/" }
     ]
    }
   ]
  },
  {
   "title": "Gameobjects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Map $tag_map_id Instance $tag_map_instanceid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "map_id" ], "type": "tag" },
      { "params": [ "map_instanceid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "map_gameobjects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "realm", "operator": "=~", "value": "/^$realm$/" }
     ]
    }
   ]
  }
 ]
}