-- Branding economy/crafting (§8.6): recipe table consumed by EconomyMgr.
-- inputs (materials + fragments, config-mapped item entries) -> output item + character XP.
CREATE TABLE IF NOT EXISTS `branding_recipe` (
    `id` INT UNSIGNED NOT NULL COMMENT 'Recipe id used by .branding craft <id>',
    `materials` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Material items consumed (Branding.Economy.MaterialItemId)',
    `fragments` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Fragment items consumed (Branding.Economy.FragmentItemId)',
    `output_item` INT UNSIGNED NOT NULL COMMENT 'item_template.entry produced (1 unit)',
    `char_xp` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Character XP granted on craft',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='mod-branding closed-loop crafting recipes';

-- output_item repointed off placeholder cloth onto the Branded outputs (#27 §8.6); reagent counts
-- mirror the native craft spells in modules/mod-branding/data/sql/db-world (the #29 lockstep).
-- Generated by tools/branding-craft (`branding-craft recipe-sql`).
DELETE FROM `branding_recipe` WHERE `id` IN (1, 2, 3);
INSERT INTO `branding_recipe` (`id`, `materials`, `fragments`, `output_item`, `char_xp`) VALUES
    (1, 5, 0, 190010, 100),
    (2, 10, 5, 190011, 250),
    (3, 20, 10, 190012, 600);
