-- Rocknot's Ale and Phalanx: TBC Anniversary 2.5.6 build 69546, 2026-09-06.
-- Corner/door staging originally implemented by Cala in CMaNGOS (563770518af7).
-- The fallback corner facing is from ratkosrb's vMaNGOS spawn update (55ba8c15866c).
UPDATE `creature` SET `position_x` = 847.84796, `position_y` = -230.06673, `position_z` = -43.61398, `orientation` = 1.64061, `VerifiedBuild` = 69546 WHERE `guid` = 46615 AND `id` = 9502;
UPDATE `creature` SET `position_x` = 891.1985, `position_y` = -197.924, `position_z` = -43.620373, `orientation` = 3.2114058, `VerifiedBuild` = 69546 WHERE `guid` = 46614 AND `id` = 9503;

-- The first spline is replaced while running. Keep its turn and the final stop;
-- intermediate navigation points are generated by the server's movement maps.
DELETE FROM `waypoint_data` WHERE `id` = 95020;
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `velocity`, `delay`, `smoothTransition`, `move_type`, `action`, `action_chance`, `wpguid`) VALUES
(95020, 1, 865.3834, -219.31128, -43.7037, NULL, 8, 0, 0, 1, 0, 100, 0),
(95020, 2, 867.29456, -222.6452, -43.72592, 2.0071287, 8, 0, 0, 1, 0, 100, 0);

-- Positions on the captured route, with waits at the three actual keg stops.
-- Redirected spline endpoints that Rocknot never reaches are not additional stops.
DELETE FROM `script_waypoint` WHERE `entry` = 9503;
INSERT INTO `script_waypoint` (`entry`, `pointid`, `location_x`, `location_y`, `location_z`, `waittime`, `point_comment`) VALUES
(9503, 0, 884.94965, -193.1537, -43.7037, 0, 'Rocknot - Approach kegs'),
(9503, 1, 879.8619, -189.96124, -43.703705, 0, 'Rocknot - Approach first keg'),
(9503, 2, 871.6734, -185.76802, -43.70371, 4700, 'Rocknot - First keg'),
(9503, 3, 867.2741, -190.41896, -43.70371, 0, 'Rocknot - Turn toward second keg'),
(9503, 4, 860.8991, -191.71492, -43.703705, 3100, 'Rocknot - Second keg'),
(9503, 5, 858.04724, -193.25536, -43.703705, 0, 'Rocknot - Approach final keg'),
(9503, 6, 855.1874, -194.80013, -43.703705, 0, 'Rocknot - Approach final keg'),
(9503, 7, 851.37866, -196.69437, -43.703705, 0, 'Rocknot - Break keg and remain stunned');

DELETE FROM `creature_text` WHERE `CreatureID` = 9502 AND `GroupID` = 0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(9502, 0, 0, 'Violence!  Property damage!  None shall pass!!', 14, 0, 100, 0, 0, 0, 5300, 0, 'Phalanx - Door announcement');
UPDATE `creature_text` SET `Text` = 'I want more ale!  Give me more ale!' WHERE `CreatureID` = 9503 AND `GroupID` = 1 AND `ID` = 0;
