INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1561621303750042400');

-- Generated by Event Horizon - SAI Editor (http://devsource-eventhorizon.tk/)

-- Flatland Prowler
SET @ENTRY := 3566;
SET @SOURCETYPE := 0;

DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=@SOURCETYPE;
UPDATE creature_template SET AIName="SmartAI" WHERE entry=@ENTRY;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES 
(@ENTRY,@SOURCETYPE,0,0,11,0,100,1,0,0,0,0,11,24450,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,'Flatland Prowler - Cast Prowl on Spawn'),
(@ENTRY,@SOURCETYPE,1,0,7,0,100,1,0,0,0,0,11,24450,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,'Flatland Prowler - Cast Prowl on Evade'),
(@ENTRY,@SOURCETYPE,2,0,1,0,100,0,0,0,0,0,11,24450,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,'Flatland Prowler- Cast Prown on Out of Combat');
