-- mod-branding §16: per-school Fragments. Add branding_recipe.school so each recipe names the
-- BrandId of the Fragment it consumes; the adapter then draws from SchoolFragmentBaseItemId + school
-- (the "Fire-Branded Fragment" loop) when Branding.Economy.SchoolFragments.Enable is on, else the
-- generic Fragment. Separate rev (not an in-place regen of the #09 recipe rev) so existing DBs get
-- the column via ALTER. The repointed mirror below mirrors the native craft spells in
-- modules/mod-branding/data/sql/db-world (the #29 lockstep) -- generated by `branding-craft recipe-sql`.
ALTER TABLE `branding_recipe`
    ADD COLUMN `school` TINYINT UNSIGNED NOT NULL DEFAULT 255
    COMMENT 'BrandId of the Fragment consumed (0..14); >=15 = generic Fragment' AFTER `char_xp`;

DELETE FROM `branding_recipe` WHERE `id` IN (1, 2, 3);
INSERT INTO `branding_recipe` (`id`, `materials`, `fragments`, `output_item`, `char_xp`, `school`) VALUES
    (1, 5, 0, 190010, 100, 2),
    (2, 10, 5, 190011, 250, 0),
    (3, 20, 10, 190012, 600, 4);
