DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95026;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95026, 95026);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95025;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95025, 95025);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95024;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95024, 95024);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95023;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95023, 95023);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95022;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95022, 95022);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95021;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95021, 95021);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95020;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95020, 95020);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95019;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95019, 95019);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95018;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95018, 95018);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95017;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95017, 95017);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95016;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95016, 95016);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95015;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95015, 95015);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95014;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95014, 95014);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95013;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95013, 95013);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95012;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95012, 95012);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95011;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95011, 95011);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95010;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95010, 95010);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95009;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95009, 95009);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95008;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95008, 95008);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95007;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95007, 95007);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95006;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95006, 95006);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95005;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95005, 95005);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95004;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95004, 95004);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95003;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95003, 95003);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95002;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95002, 95002);
DELETE FROM `creature_default_trainer` WHERE `CreatureId`=95001;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (95001, 95001);
