-- mod-branding native profession crafting (#27 server content + #29 craft spells).
-- GENERATED by tools/branding-craft -- do not hand-edit; change src/branding_craft/catalog.py
-- and re-run `branding-craft world-sql`. Reagent counts here share their source with the
-- client Spell.dbc patch and the branding_recipe mirror, so the three cannot drift (#29).
-- The branding_recipe mirror itself is repointed by `branding-craft recipe-sql` (it lives in
-- the #09 loader's core pending rev, the table's single home).

-- #27 item_template: resources, Branded outputs, recipe patterns.

DELETE FROM `item_template` WHERE `entry` IN (190000, 190001, 190010, 190011, 190012, 190050, 190051, 190052);
INSERT INTO `item_template` (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `BuyPrice`, `SellPrice`, `InventoryType`, `ItemLevel`, `RequiredLevel`, `RequiredSkill`, `RequiredSkillRank`, `stackable`, `stat_type1`, `stat_value1`, `stat_type2`, `stat_value2`, `armor`, `spellid_1`, `spelltrigger_1`, `bonding`, `Material`) VALUES
    (190000, 7, 5, 'Branding Material', 6884, 1, 0, 1, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 2, 4),
    (190001, 7, 5, 'Branding Fragment', 41111, 3, 0, 1, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 5, 4),
    (190010, 4, 2, 'Branded Leather Chestguard', 48723, 2, 0, 100, 5, 187, 0, 165, 350, 1, 7, 12, 5, 8, 250, 0, 0, 5, 4),
    (190011, 4, 4, 'Branded Plate Chestpiece', 48729, 3, 0, 100, 5, 200, 0, 164, 400, 1, 7, 12, 5, 8, 250, 0, 0, 5, 4),
    (190012, 4, 1, 'Branded Cloth Robe', 48733, 3, 0, 100, 5, 213, 0, 197, 450, 1, 7, 12, 5, 8, 250, 0, 0, 5, 4),
    (190050, 9, 2, 'Pattern: Branded Leather Chestguard', 1387, 2, 0, 5000, 0, 0, 0, 165, 350, 1, 0, 0, 0, 0, 0, 1900010, 6, 1, 0),
    (190051, 9, 5, 'Pattern: Branded Plate Chestpiece', 1387, 3, 0, 5000, 0, 0, 0, 164, 400, 1, 0, 0, 0, 0, 0, 1900011, 6, 1, 0),
    (190052, 9, 3, 'Pattern: Branded Cloth Robe', 1387, 3, 0, 5000, 0, 0, 0, 197, 450, 1, 0, 0, 0, 0, 0, 1900012, 6, 1, 0);

-- #29 spell_dbc: native CREATE_ITEM craft spells (server DBC override).

DELETE FROM `spell_dbc` WHERE `ID` IN (1900010, 1900011, 1900012);
INSERT INTO `spell_dbc` (`ID`, `Attributes`, `CastingTimeIndex`, `RangeIndex`, `EquippedItemClass`, `Reagent_1`, `Reagent_2`, `ReagentCount_1`, `ReagentCount_2`, `Effect_1`, `EffectDieSides_1`, `EffectBasePoints_1`, `ImplicitTargetA_1`, `EffectItemType_1`, `Name_Lang_enUS`) VALUES
    (1900010, 64, 1, 1, -1, 190000, 0, 5, 0, 24, 1, 0, 1, 190010, 'Branded Leather Chestguard'),
    (1900011, 64, 1, 1, -1, 190000, 190001, 10, 5, 24, 1, 0, 1, 190011, 'Branded Plate Chestpiece'),
    (1900012, 64, 1, 1, -1, 190000, 190001, 20, 10, 24, 1, 0, 1, 190012, 'Branded Cloth Robe');

-- #29 skilllineability_dbc: craft spell -> profession skill line.

DELETE FROM `skilllineability_dbc` WHERE `ID` IN (1900110, 1900111, 1900112);
INSERT INTO `skilllineability_dbc` (`ID`, `SkillLine`, `Spell`, `MinSkillLineRank`, `TrivialSkillLineRankHigh`, `TrivialSkillLineRankLow`) VALUES
    (1900110, 165, 1900010, 350, 375, 350),
    (1900111, 164, 1900011, 400, 425, 400),
    (1900112, 197, 1900012, 450, 450, 450);
