name: Check pending sql for Procedure/Function
on:
  pull_request:

jobs:
  check-pending-sql:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check for Procedure/Function
        run: |
         if grep -R -q -i -E "(PROCEDURE|FUNCTION)" data/sql/updates/pending*
            then
                exit 1
            else
                exit 0
         fi
