name: Check pending SQL
on:
  pull_request:

jobs:
  check-pending-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check pending SQL
        run: source ./apps/ci/ci-pending.sh
