name: pch-build

on:
  push:
    branches:
      - 'master'
      - 'test-staging'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-24.04
            compiler:
              CC: clang-18
              CXX: clang++-18
          - os: ubuntu-26.04
            compiler:
              CC: clang-20
              CXX: clang++-20
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.compiler.CC }}-pch
    if: github.repository == 'mod-playerbots/azerothcore-wotlk' && !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux-build
        with:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
          pch: true
          modules: true   # optional: include modules in PCH build