name: cpp-check
on:
  push:
    branches:
      - "master"
    paths:
      - src/**
      - "!README.md"
      - "!docs/**"
  pull_request:
    paths:
      - src/**
      - "!README.md"
      - "!docs/**"

jobs:
  cpp-check:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    if: github.repository == 'azerothcore/azerothcore-wotlk'
    name: cpp check
    steps:
      - uses: actions/checkout@v3
      - name: cpp check
        run: |
          sudo apt update -y
          sudo apt install -y cppcheck
          cppcheck --force --inline-suppr \
            -i src/server/game/Achievements/AchievementMgr.cpp \
            -i src/server/game/AuctionHouse/AuctionHouseMgr.cpp \
            -i src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp \
            -i src/server/game/DungeonFinding/LFGMgr.cpp \
            -i src/server/game/Entities/GameObject/GameObject.cpp \
            -i src/server/game/Entities/Pet/Pet.cpp \
            -i src/server/game/Entities/Player/Player.cpp \
            src/
