/*
 * This file is part of the AzerothCore Project. See AUTHORS file for Copyright information
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef WORLD_STATE_DEFINES_H
#define WORLD_STATE_DEFINES_H

enum WorldStateIDs
{
    // Scourge Invasion
    WORLD_STATE_SCOURGE_INVASION_VICTORIES = 2219,

    // Active Invasion Indicators
    WORLD_STATE_SCOURGE_INVASION_WINTERSPRING        = 2259,
    WORLD_STATE_SCOURGE_INVASION_AZSHARA             = 2260,
    WORLD_STATE_SCOURGE_INVASION_BLASTED_LANDS       = 2261,
    WORLD_STATE_SCOURGE_INVASION_BURNING_STEPPES     = 2262,
    WORLD_STATE_SCOURGE_INVASION_TANARIS             = 2263,
    WORLD_STATE_SCOURGE_INVASION_EASTERN_PLAGUELANDS = 2264,

    // Active Necropoli
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_AZSHARA             = 2279,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_BLASTED_LANDS       = 2280,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_BURNING_STEPPES     = 2281,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_EASTERN_PLAGUELANDS = 2282,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_TANARIS             = 2283,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_WINTERSPRING        = 2284,

    // Arena
    WORLD_STATE_ARENA_SEASON_PROGRESS     = 3191,
    WORLD_STATE_ARENA_ALIVE_PLAYERS_GREEN = 3600,
    WORLD_STATE_ARENA_ALIVE_PLAYERS_GOLD  = 3601,
    WORLD_STATE_ARENA_SEASON_ID           = 3901,

    // Sun's Reach Reclamation
    WORLD_STATE_QUEL_DANAS_MUSIC       = 3426,
    WORLD_STATE_QUEL_DANAS_HARBOR      = 3238,
    WORLD_STATE_QUEL_DANAS_ALCHEMY_LAB = 3223,
    WORLD_STATE_QUEL_DANAS_ARMORY      = 3233,
    WORLD_STATE_QUEL_DANAS_SANCTUM     = 3244,
    WORLD_STATE_QUEL_DANAS_PORTAL      = 3269,
    WORLD_STATE_QUEL_DANAS_ANVIL       = 3228,
    WORLD_STATE_QUEL_DANAS_MONUMENT    = 3275,

    // Sunwell Gate
    WORLD_STATE_AGAMATH_THE_FIRST_GATE_HEALTH    = 3253, // guessed, potentially wrong
    WORLD_STATE_ROHENDOR_THE_SECOND_GATE_HEALTH  = 3255,
    WORLD_STATE_ARCHONISUS_THE_FINAL_GATE_HEALTH = 3257,

    // Wintergrasp
    WORLD_STATE_BATTLEFIELD_WG_VEHICLE_H              = 3490,
    WORLD_STATE_BATTLEFIELD_WG_MAX_VEHICLE_H          = 3491,
    WORLD_STATE_BATTLEFIELD_WG_VEHICLE_A              = 3680,
    WORLD_STATE_BATTLEFIELD_WG_MAX_VEHICLE_A          = 3681,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_K_W           = 3698,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_K_E           = 3699,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_NW            = 3700,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_NE            = 3701,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_SW            = 3702,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_SE            = 3703,
    WORLD_STATE_BATTLEFIELD_WG_SHOW                   = 3710,
    WORLD_STATE_BATTLEFIELD_WG_CLOCK                  = 3781,
    WORLD_STATE_BATTLEFIELD_WG_ACTIVE                 = 3801,
    WORLD_STATE_BATTLEFIELD_WG_DEFENDER               = 3802,
    WORLD_STATE_BATTLEFIELD_WG_ATTACKER               = 3803,
    WORLD_STATE_BATTLEFIELD_WG_CONTROL                = 3804, // Shows on the map who controls WG
    WORLD_STATE_BATTLEFIELD_WG_HORDE_KEEP_CAPTURED    = 4022,
    WORLD_STATE_BATTLEFIELD_WG_ALLIANCE_KEEP_CAPTURED = 4023,
    WORLD_STATE_BATTLEFIELD_WG_HORDE_KEEP_DEFENDED    = 4024,
    WORLD_STATE_BATTLEFIELD_WG_ALLIANCE_KEEP_DEFENDED = 4025,
    WORLD_STATE_BATTLEFIELD_WG_CLOCK_TEXTS            = 4354,
    WORLD_STATE_BATTLEFIELD_WG_ICON_ACTIVE            = 4375, // Activates "ice" icon

    // Alterac Valley
    WORLD_STATE_BATTLEGROUND_AV_STORMPIKE_LIEUTENANTS = 950,
    WORLD_STATE_BATTLEGROUND_AV_STORMPIKE_COMMANDERS  = 962,
    WORLD_STATE_BATTLEGROUND_AV_UNK_0                 = 964,
    WORLD_STATE_BATTLEGROUND_AV_UNK_1                 = 966,
    WORLD_STATE_BATTLEGROUND_AV_STONEHEART_H_C        = 1301,
    WORLD_STATE_BATTLEGROUND_AV_STONEHEART_A_C        = 1302,
    WORLD_STATE_BATTLEGROUND_AV_STONEHEART_H_A        = 1303,
    WORLD_STATE_BATTLEGROUND_AV_STONEHEART_A_A        = 1304,
    WORLD_STATE_BATTLEGROUND_AV_AID_A_C               = 1325,
    WORLD_STATE_BATTLEGROUND_AV_AID_A_A               = 1326,
    WORLD_STATE_BATTLEGROUND_AV_AID_H_C               = 1327,
    WORLD_STATE_BATTLEGROUND_AV_AID_H_A               = 1328,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFHUT_A_C      = 1329,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFHUT_H_C      = 1330,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFHUT_A_A      = 1331,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFHUT_H_A      = 1332,
    WORLD_STATE_BATTLEGROUND_AV_PIKEGRAVE_A_C         = 1333,
    WORLD_STATE_BATTLEGROUND_AV_PIKEGRAVE_H_C         = 1334,
    WORLD_STATE_BATTLEGROUND_AV_PIKEGRAVE_A_A         = 1335,
    WORLD_STATE_BATTLEGROUND_AV_PIKEGRAVE_H_A         = 1336,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLF_A_C         = 1337,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLF_H_C         = 1338,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLF_A_A         = 1339,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLF_H_A         = 1340,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_A_C          = 1341,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_H_C          = 1342,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_A_A          = 1343,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_H_A          = 1344,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_A_C          = 1346,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_H_C          = 1347,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_A_A          = 1348,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_H_A          = 1349,
    WORLD_STATE_BATTLEGROUND_AV_S_MINE_A              = 1355,
    WORLD_STATE_BATTLEGROUND_AV_S_MINE_H              = 1356,
    WORLD_STATE_BATTLEGROUND_AV_S_MINE_N              = 1357,
    WORLD_STATE_BATTLEGROUND_AV_N_MINE_A              = 1358,
    WORLD_STATE_BATTLEGROUND_AV_N_MINE_H              = 1359,
    WORLD_STATE_BATTLEGROUND_AV_N_MINE_N              = 1360,
    WORLD_STATE_BATTLEGROUND_AV_DUNS_CONTROLLED       = 1361,
    WORLD_STATE_BATTLEGROUND_AV_DUNN_CONTROLLED       = 1362,
    WORLD_STATE_BATTLEGROUND_AV_ICEWING_CONTROLLED    = 1363,
    WORLD_STATE_BATTLEGROUND_AV_STONEH_CONTROLLED     = 1364,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFW_DESTROYED  = 1365,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFE_DESTROYED  = 1366,
    WORLD_STATE_BATTLEGROUND_AV_TOWERPOINT_DESTROYED  = 1367,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_DESTROYED    = 1368,
    WORLD_STATE_BATTLEGROUND_AV_UNK_2                 = 1369,
    WORLD_STATE_BATTLEGROUND_AV_DUNS_DESTROYED        = 1370,
    WORLD_STATE_BATTLEGROUND_AV_DUNN_DESTROYED        = 1371,
    WORLD_STATE_BATTLEGROUND_AV_ICEWING_DESTROYED     = 1372,
    WORLD_STATE_BATTLEGROUND_AV_STONEH_DESTROYED      = 1373,
    WORLD_STATE_BATTLEGROUND_AV_DUNN_UNUSED           = 1374, // Unused
    WORLD_STATE_BATTLEGROUND_AV_DUNS_UNUSED           = 1375, // Unused
    WORLD_STATE_BATTLEGROUND_AV_ICEWING_UNUSED        = 1376, // Unused
    WORLD_STATE_BATTLEGROUND_AV_STONEH_UNUSED         = 1377, // Unused
    WORLD_STATE_BATTLEGROUND_AV_DUNS_ASSAULTED        = 1378,
    WORLD_STATE_BATTLEGROUND_AV_DUNN_ASSAULTED        = 1379,
    WORLD_STATE_BATTLEGROUND_AV_ICEWING_ASSAULTED     = 1380,
    WORLD_STATE_BATTLEGROUND_AV_STONEH_ASSAULTED      = 1381,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFW_CONTROLLED = 1382,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFE_CONTROLLED = 1383,
    WORLD_STATE_BATTLEGROUND_AV_TOWERPOINT_CONTROLLED = 1384,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_CONTROLLED   = 1385,
    WORLD_STATE_BATTLEGROUND_AV_UNK_3                 = 1386,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFW_ASSAULTED  = 1387,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFE_ASSAULTED  = 1388,
    WORLD_STATE_BATTLEGROUND_AV_TOWERPOINT_ASSAULTED  = 1389,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_ASSAULTED    = 1390,
    WORLD_STATE_BATTLEGROUND_AV_UNK_4                 = 1391,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFW_UNUSED     = 1392, // Unused
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFE_UNUSED     = 1393, // Unused
    WORLD_STATE_BATTLEGROUND_AV_TOWERPOINT_UNUSED     = 1394, // Unused
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_UNUSED       = 1395, // Unused
    WORLD_STATE_BATTLEGROUND_AV_UNK_5                 = 1396,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_N            = 1966,
    WORLD_STATE_BATTLEGROUND_AV_ALLIANCE_SCORE        = 3127,
    WORLD_STATE_BATTLEGROUND_AV_HORDE_SCORE           = 3128,
    WORLD_STATE_BATTLEGROUND_AV_SHOW_HORDE_SCORE      = 3133,
    WORLD_STATE_BATTLEGROUND_AV_SHOW_ALLIANCE_SCORE   = 3134,

    // Warsong Gulch
    WORLD_STATE_BATTLEGROUND_WS_UNK_0                  = 1545, // set to 1 on alliance flag pickup...
    WORLD_STATE_BATTLEGROUND_WS_UNK_1                  = 1546, // set to 1 on horde flag pickup, after drop it's -1
    WORLD_STATE_BATTLEGROUND_WS_UNK_2                  = 1547,
    WORLD_STATE_BATTLEGROUND_WS_FLAG_CAPTURES_ALLIANCE = 1581,
    WORLD_STATE_BATTLEGROUND_WS_FLAG_CAPTURES_HORDE    = 1582,
    WORLD_STATE_BATTLEGROUND_WS_FLAG_CAPTURES_MAX      = 1601, // unk
    WORLD_STATE_BATTLEGROUND_WS_FLAG_STATE_HORDE       = 2338, // (0 - hide, 1 - flag ok, 2 - flag picked up (flashing), 3 - flag picked up (not flashing)
    WORLD_STATE_BATTLEGROUND_WS_FLAG_STATE_ALLIANCE    = 2339, // (0 - hide, 1 - flag ok, 2 - flag picked up (flashing), 3 - flag picked up (not flashing)
    WORLD_STATE_BATTLEGROUND_WS_STATE_TIMER_ACTIVE     = 4247,
    WORLD_STATE_BATTLEGROUND_WS_STATE_TIMER            = 4248,

    // Arathi Basin
    WORLD_STATE_BATTLEGROUND_AB_STABLE_STATE_ALLIANCE                = 1767,
    WORLD_STATE_BATTLEGROUND_AB_STABLE_STATE_HORDE                   = 1768,
    WORLD_STATE_BATTLEGROUND_AB_STABLE_STATE_CONTROLLED_ALLIANCE     = 1769,
    WORLD_STATE_BATTLEGROUND_AB_STABLE_STATE_CONTROLLED_HORDE        = 1770,
    WORLD_STATE_BATTLEGROUND_AB_FARM_STATE_ALLIANCE                  = 1772,
    WORLD_STATE_BATTLEGROUND_AB_FARM_STATE_HORDE                     = 1773,
    WORLD_STATE_BATTLEGROUND_AB_FARM_STATE_CONTROLLED_ALLIANCE       = 1774,
    WORLD_STATE_BATTLEGROUND_AB_FARM_STATE_CONTROLLED_HORDE          = 1775,
    WORLD_STATE_BATTLEGROUND_AB_RESOURCES_ALLIANCE                   = 1776,
    WORLD_STATE_BATTLEGROUND_AB_RESOURCES_HORDE                      = 1777,
    WORLD_STATE_BATTLEGROUND_AB_OCCUPIED_BASES_HORDE                 = 1778,
    WORLD_STATE_BATTLEGROUND_AB_OCCUPIED_BASES_ALLIANCE              = 1779,
    WORLD_STATE_BATTLEGROUND_AB_RESOURCES_MAX                        = 1780,
    WORLD_STATE_BATTLEGROUND_AB_BLACKSMITH_STATE_ALLIANCE            = 1782,
    WORLD_STATE_BATTLEGROUND_AB_BLACKSMITH_STATE_HORDE               = 1783,
    WORLD_STATE_BATTLEGROUND_AB_BLACKSMITH_STATE_CONTROLLED_ALLIANCE = 1784,
    WORLD_STATE_BATTLEGROUND_AB_BLACKSMITH_STATE_CONTROLLED_HORDE    = 1785,
    WORLD_STATE_BATTLEGROUND_AB_GOLDMINE_STATE_ALLIANCE              = 1787,
    WORLD_STATE_BATTLEGROUND_AB_GOLDMINE_STATE_HORDE                 = 1788,
    WORLD_STATE_BATTLEGROUND_AB_GOLDMINE_STATE_CONTROLLED_ALLIANCE   = 1789,
    WORLD_STATE_BATTLEGROUND_AB_GOLDMINE_STATE_CONTROLLED_HORDE      = 1790,
    WORLD_STATE_BATTLEGROUND_AB_LUMBERMILL_STATE_ALLIANCE            = 1792,
    WORLD_STATE_BATTLEGROUND_AB_LUMBERMILL_STATE_HORDE               = 1793,
    WORLD_STATE_BATTLEGROUND_AB_LUMBERMILL_STATE_CONTROLLED_ALLIANCE = 1794,
    WORLD_STATE_BATTLEGROUND_AB_LUMBERMILL_STATE_CONTROLLED_HORDE    = 1795,
    WORLD_STATE_BATTLEGROUND_AB_STABLE_ICON                          = 1842, // 1 - uncontrolled
    WORLD_STATE_BATTLEGROUND_AB_GOLDMINE_ICON                        = 1843, // 1 - uncontrolled
    WORLD_STATE_BATTLEGROUND_AB_LUMBERMILL_ICON                      = 1844, // 1 - uncontrolled
    WORLD_STATE_BATTLEGROUND_AB_FARM_ICON                            = 1845, // 1 - uncontrolled
    WORLD_STATE_BATTLEGROUND_AB_BLACKSMITH_ICON                      = 1846, // 1 - uncontrolled
    WORLD_STATE_BATTLEGROUND_AB_UNK                                  = 1861,
    WORLD_STATE_BATTLEGROUND_AB_RESOURCES_WARNING                    = 1955,

    // Eye of the Storm
    WORLD_STATE_BATTLEGROUND_EY_PROGRESS_BAR_SHOW               = 2718, //1 init, 0 druhy send - bez messagu, 1 = controlled aliance // Capturing progress-bar (1 - show, 0 - hide)
    WORLD_STATE_BATTLEGROUND_EY_PROGRESS_BAR_STATUS             = 2719, //50 init!, 48 ... hordak bere .. 33 .. 0 = full 100% hordacky, 100 = full alliance // Capturing progress-bar (0 - left, 100 - right)
    WORLD_STATE_BATTLEGROUND_EY_PROGRESS_BAR_PERCENT_GREY       = 2720, //100 = empty (only grey), 0 = blue|red (no grey)
    WORLD_STATE_BATTLEGROUND_EY_BLOOD_ELF_UNCONTROL             = 2722, // 1 - yes, 0 - no
    WORLD_STATE_BATTLEGROUND_EY_BLOOD_ELF_ALLIANCE_CONTROL      = 2723,
    WORLD_STATE_BATTLEGROUND_EY_BLOOD_ELF_HORDE_CONTROL         = 2724,
    WORLD_STATE_BATTLEGROUND_EY_FEL_REAVER_UNCONTROL            = 2725, // 1 - yes, 0 - no
    WORLD_STATE_BATTLEGROUND_EY_FEL_REAVER_ALLIANCE_CONTROL     = 2726,
    WORLD_STATE_BATTLEGROUND_EY_FEL_REAVER_HORDE_CONTROL        = 2727,
    WORLD_STATE_BATTLEGROUND_EY_MAGE_TOWER_UNCONTROL            = 2728, // 1 - yes, 0 - no
    WORLD_STATE_BATTLEGROUND_EY_MAGE_TOWER_HORDE_CONTROL        = 2729,
    WORLD_STATE_BATTLEGROUND_EY_MAGE_TOWER_ALLIANCE_CONTROL     = 2730,
    WORLD_STATE_BATTLEGROUND_EY_DRAENEI_RUINS_UNCONTROL         = 2731, // 1 - yes, 0 - no
    WORLD_STATE_BATTLEGROUND_EY_DRAENEI_RUINS_ALLIANCE_CONTROL  = 2732,
    WORLD_STATE_BATTLEGROUND_EY_DRAENEI_RUINS_HORDE_CONTROL     = 2733,
    WORLD_STATE_BATTLEGROUND_EY_DRAENEI_RUINS_HORDE_CONFLICT    = 2737,
    WORLD_STATE_BATTLEGROUND_EY_DRAENEI_RUINS_ALLIANCE_CONFLICT = 2738,
    WORLD_STATE_BATTLEGROUND_EY_FEL_REAVER_ALLIANCE_CONFLICT    = 2739,
    WORLD_STATE_BATTLEGROUND_EY_FEL_REAVER_HORDE_CONFLICT       = 2740,
    WORLD_STATE_BATTLEGROUND_EY_MAGE_TOWER_ALLIANCE_CONFLICT    = 2741,
    WORLD_STATE_BATTLEGROUND_EY_MAGE_TOWER_HORDE_CONFLICT       = 2742,
    WORLD_STATE_BATTLEGROUND_EY_UNK_0                           = 2565, // 142, constant?
    WORLD_STATE_BATTLEGROUND_EY_UNK_1                           = 2735, // 0 at start
    WORLD_STATE_BATTLEGROUND_EY_UNK_2                           = 2736, // 0 at start
    WORLD_STATE_BATTLEGROUND_EY_UNK_3                           = 3085, // 379, constant?
    WORLD_STATE_BATTLEGROUND_EY_ALLIANCE_RESOURCES              = 2749,
    WORLD_STATE_BATTLEGROUND_EY_HORDE_RESOURCES                 = 2750,
    WORLD_STATE_BATTLEGROUND_EY_ALLIANCE_BASE                   = 2752,
    WORLD_STATE_BATTLEGROUND_EY_HORDE_BASE                      = 2753,
    WORLD_STATE_BATTLEGROUND_EY_FLAG                            = 2757, // 1 - show, 0 - hide (doesn't work exactly this way!)
    WORLD_STATE_BATTLEGROUND_EY_FLAG_STATE_ALLIANCE             = 2769, // 0 - hide, 1 - show stats, 2 - Alliance picked up the flag
    WORLD_STATE_BATTLEGROUND_EY_FLAG_STATE_HORDE                = 2770, // 0 - hide, 1 - show stats, 2 - Horde picked up the flag

    // Isle of Conquest
    WORLD_STATE_BATTLEGROUND_IC_ALLIANCE_REINFORCEMENT_SET = 4221,
    WORLD_STATE_BATTLEGROUND_IC_HORDE_REINFORCEMENT_SET    = 4222,
    WORLD_STATE_BATTLEGROUND_IC_ALLIANCE_REINFORCEMENT     = 4226,
    WORLD_STATE_BATTLEGROUND_IC_HORDE_REINFORCEMENT        = 4227,
    WORLD_STATE_BATTLEGROUND_IC_WORKSHOP_CONFLICT_A        = 4228,
    WORLD_STATE_BATTLEGROUND_IC_WORKSHOP_CONTROLLED_A      = 4229,
    WORLD_STATE_BATTLEGROUND_IC_WORKSHOP_CONTROLLED_H      = 4230,
    WORLD_STATE_BATTLEGROUND_IC_UNK                        = 4243,
    WORLD_STATE_BATTLEGROUND_IC_WORKSHOP_CONFLICT_H        = 4293,
    WORLD_STATE_BATTLEGROUND_IC_WORKSHOP_UNCONTROLLED      = 4294,
    WORLD_STATE_BATTLEGROUND_IC_HANGAR_UNCONTROLLED        = 4296,
    WORLD_STATE_BATTLEGROUND_IC_HANGAR_CONFLICT_H          = 4297,
    WORLD_STATE_BATTLEGROUND_IC_HANGAR_CONTROLLED_H        = 4298,
    WORLD_STATE_BATTLEGROUND_IC_HANGAR_CONTROLLED_A        = 4299,
    WORLD_STATE_BATTLEGROUND_IC_HANGAR_CONFLICT_A          = 4300,
    WORLD_STATE_BATTLEGROUND_IC_DOCKS_UNCONTROLLED         = 4301,
    WORLD_STATE_BATTLEGROUND_IC_DOCKS_CONFLICT_H           = 4302,
    WORLD_STATE_BATTLEGROUND_IC_DOCKS_CONTROLLED_H         = 4303,
    WORLD_STATE_BATTLEGROUND_IC_DOCKS_CONTROLLED_A         = 4304,
    WORLD_STATE_BATTLEGROUND_IC_DOCKS_CONFLICT_A           = 4305,
    WORLD_STATE_BATTLEGROUND_IC_QUARRY_UNCONTROLLED        = 4306,
    WORLD_STATE_BATTLEGROUND_IC_QUARRY_CONFLICT_H          = 4307,
    WORLD_STATE_BATTLEGROUND_IC_QUARRY_CONTROLLED_H        = 4308,
    WORLD_STATE_BATTLEGROUND_IC_QUARRY_CONTROLLED_A        = 4309,
    WORLD_STATE_BATTLEGROUND_IC_QUARRY_CONFLICT_A          = 4310,
    WORLD_STATE_BATTLEGROUND_IC_REFINERY_UNCONTROLLED      = 4311,
    WORLD_STATE_BATTLEGROUND_IC_REFINERY_CONFLICT_H        = 4312,
    WORLD_STATE_BATTLEGROUND_IC_REFINERY_CONTROLLED_H      = 4313,
    WORLD_STATE_BATTLEGROUND_IC_REFINERY_CONTROLLED_A      = 4314,
    WORLD_STATE_BATTLEGROUND_IC_REFINERY_CONFLICT_A        = 4315,
    WORLD_STATE_BATTLEGROUND_IC_GATE_FRONT_H_WS_CLOSED     = 4317,
    WORLD_STATE_BATTLEGROUND_IC_GATE_WEST_H_WS_CLOSED      = 4318,
    WORLD_STATE_BATTLEGROUND_IC_GATE_EAST_H_WS_CLOSED      = 4319,
    WORLD_STATE_BATTLEGROUND_IC_GATE_EAST_H_WS_OPEN        = 4320,
    WORLD_STATE_BATTLEGROUND_IC_GATE_WEST_H_WS_OPEN        = 4321,
    WORLD_STATE_BATTLEGROUND_IC_GATE_FRONT_H_WS_OPEN       = 4322,
    WORLD_STATE_BATTLEGROUND_IC_GATE_FRONT_A_WS_OPEN       = 4323,
    WORLD_STATE_BATTLEGROUND_IC_GATE_WEST_A_WS_OPEN        = 4324,
    WORLD_STATE_BATTLEGROUND_IC_GATE_EAST_A_WS_OPEN        = 4325,
    WORLD_STATE_BATTLEGROUND_IC_GATE_EAST_A_WS_CLOSED      = 4326,
    WORLD_STATE_BATTLEGROUND_IC_GATE_WEST_A_WS_CLOSED      = 4327,
    WORLD_STATE_BATTLEGROUND_IC_GATE_FRONT_A_WS_CLOSED     = 4328,
    WORLD_STATE_BATTLEGROUND_IC_ALLIANCE_KEEP_CONTROLLED_A = 4339,
    WORLD_STATE_BATTLEGROUND_IC_ALLIANCE_KEEP_CONTROLLED_H = 4340,
    WORLD_STATE_BATTLEGROUND_IC_ALLIANCE_KEEP_UNCONTROLLED = 4341,
    WORLD_STATE_BATTLEGROUND_IC_ALLIANCE_KEEP_CONFLICT_A   = 4342,
    WORLD_STATE_BATTLEGROUND_IC_ALLIANCE_KEEP_CONFLICT_H   = 4343,
    WORLD_STATE_BATTLEGROUND_IC_HORDE_KEEP_CONTROLLED_A    = 4344,
    WORLD_STATE_BATTLEGROUND_IC_HORDE_KEEP_CONTROLLED_H    = 4345,
    WORLD_STATE_BATTLEGROUND_IC_HORDE_KEEP_UNCONTROLLED    = 4346,
    WORLD_STATE_BATTLEGROUND_IC_HORDE_KEEP_CONFLICT_A      = 4347,
    WORLD_STATE_BATTLEGROUND_IC_HORDE_KEEP_CONFLICT_H      = 4348,

    // Strand of the Ancients
    // Gates: 1-3 A defend, 4-6 H defend, 7-9 unk defend, 1 - ok, 2 - half destroyed, 3 - destroyed
    WORLD_STATE_BATTLEGROUND_SA_TIMER_MINUTES               = 3559,
    WORLD_STATE_BATTLEGROUND_SA_TIMER_SECONDS_FIRST_DIGIT   = 3560,
    WORLD_STATE_BATTLEGROUND_SA_TIMER_SECONDS_SECOND_DIGIT  = 3561,
    WORLD_STATE_BATTLEGROUND_SA_ENABLE_TIMER                = 3564, // previously mislabelled? (Alliance Attacker)
    WORLD_STATE_BATTLEGROUND_SA_HORDE_ATTACKER              = 3565, // mislabelled?
    WORLD_STATE_BATTLEGROUND_SA_BONUS_TIMER                 = 3571, // bonus timer (1 - on, 0 - off)
    WORLD_STATE_BATTLEGROUND_SA_PURPLE_GATE                 = 3614, // Gate of Purple Amethyst
    WORLD_STATE_BATTLEGROUND_SA_RED_GATE                    = 3617, // Gate of Red Sun
    WORLD_STATE_BATTLEGROUND_SA_BLUE_GATE                   = 3620, // Gate of Blue Sapphire
    WORLD_STATE_BATTLEGROUND_SA_GREEN_GATE                  = 3623, // Gate of Green Emerald
    WORLD_STATE_BATTLEGROUND_SA_LEFT_ATTACK_TOKEN_ALLIANCE  = 3626,
    WORLD_STATE_BATTLEGROUND_SA_RIGHT_ATTACK_TOKEN_ALLIANCE = 3627,
    WORLD_STATE_BATTLEGROUND_SA_RIGHT_ATTACK_TOKEN_HORDE    = 3628,
    WORLD_STATE_BATTLEGROUND_SA_LEFT_ATTACK_TOKEN_HORDE     = 3629,
    WORLD_STATE_BATTLEGROUND_SA_ALLIANCE_DEFENSE_TOKEN      = 3630,
    WORLD_STATE_BATTLEGROUND_SA_HORDE_DEFENSE_TOKEN         = 3631,
    WORLD_STATE_BATTLEGROUND_SA_RIGHT_GY_HORDE              = 3632,
    WORLD_STATE_BATTLEGROUND_SA_LEFT_GY_HORDE               = 3633,
    WORLD_STATE_BATTLEGROUND_SA_CENTER_GY_HORDE             = 3634,
    WORLD_STATE_BATTLEGROUND_SA_LEFT_GY_ALLIANCE            = 3635,
    WORLD_STATE_BATTLEGROUND_SA_RIGHT_GY_ALLIANCE           = 3636,
    WORLD_STATE_BATTLEGROUND_SA_CENTER_GY_ALLIANCE          = 3637,
    WORLD_STATE_BATTLEGROUND_SA_YELLOW_GATE                 = 3638, // Gate of Yellow Moon
    WORLD_STATE_BATTLEGROUND_SA_ANCIENT_GATE                = 3849, // Gate of Temple
    WORLD_STATE_BATTLEGROUND_SA_ALLIANCE_ATTACKS            = 4352,
    WORLD_STATE_BATTLEGROUND_SA_HORDE_ATTACKS               = 4353,

    // Blade's Edge Arena
    WORLD_STATE_BATTLEGROUND_BE_ARENA_GOLD  = 2544,
    WORLD_STATE_BATTLEGROUND_BE_ARENA_GREEN = 2545,
    WORLD_STATE_BATTLEGROUND_BE_ARENA_SHOW  = 2547,

    // Nagrand Arena
    WORLD_STATE_BATTLEGROUND_NA_ARENA_GOLD  = 2575,
    WORLD_STATE_BATTLEGROUND_NA_ARENA_GREEN = 2576,
    WORLD_STATE_BATTLEGROUND_NA_ARENA_SHOW  = 2577,

    // Ruins of Lordaeron
    WORLD_STATE_BATTLEGROUND_RL_ARENA_GOLD  = 3000,
    WORLD_STATE_BATTLEGROUND_RL_ARENA_GREEN = 3001,
    WORLD_STATE_BATTLEGROUND_RL_ARENA_SHOW  = 3002,

    // Dalaran Sewers
    WORLD_STATE_BATTLEGROUND_DS_ARENA_GREEN = 3600,
    WORLD_STATE_BATTLEGROUND_DS_ARENA_GOLD  = 3601,
    WORLD_STATE_BATTLEGROUND_DS_ARENA_SHOW  = 3610,

    // The Ring of Valor
    WORLD_STATE_BATTLEGROUND_RV_ARENA_GREEN = 3600, // Used generically for all arenas
    WORLD_STATE_BATTLEGROUND_RV_ARENA_GOLD  = 3601, // Used generically for all arenas
    WORLD_STATE_BATTLEGROUND_RV_ARENA_SHOW  = 3610,

    // The Silithyst Must Flow - Silithus Outdoor PvP
    WORLD_STATE_OPVP_SI_GATHERED_A    = 2313,
    WORLD_STATE_OPVP_SI_GATHERED_H    = 2314,
    WORLD_STATE_OPVP_SI_SILITHYST_MAX = 2317,

    // A Game of Towers - Eastern Plaguelands Outdoor PvP
    WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_A        = 2327,
    WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_H        = 2328,
    WORLD_STATE_OPVP_EP_NORTHPASSTOWER_N        = 2352,
    WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N       = 2353,
    WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_H     = 2353, // 2367 not present! use neutral!
    WORLD_STATE_OPVP_EP_EASTWALLTOWER_A         = 2354,
    WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_N       = 2355,
    WORLD_STATE_OPVP_EP_EASTWALLTOWER_H         = 2356,
    WORLD_STATE_OPVP_EP_EASTWALLTOWER_N_A       = 2359, // ally conquested
    WORLD_STATE_OPVP_EP_EASTWALLTOWER_N_H       = 2360,
    WORLD_STATE_OPVP_EP_EASTWALLTOWER_N         = 2361,
    WORLD_STATE_OPVP_EP_NORTHPASSTOWER_N_A      = 2362,
    WORLD_STATE_OPVP_EP_NORTHPASSTOWER_N_H      = 2363, // GENERAL_WORLDSTATES_08
    WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_A     = 2366,
    WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_A       = 2370,
    WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_H       = 2371,
    WORLD_STATE_OPVP_EP_NORTHPASSTOWER_A        = 2372,
    WORLD_STATE_OPVP_EP_NORTHPASSTOWER_H        = 2373,
    WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_N_A     = 2374,
    WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_N_H     = 2375,
    WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_A       = 2378,
    WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_H       = 2379,
    WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY = 2426, // GENERAL_WORLDSTATES_01 "Progress: %2427w"
    WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_POS     = 2427, // GENERAL_WORLDSTATES_02
    WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_N       = 2428, // GENERAL_WORLDSTATES_03
    WORLD_STATE_OPVP_EP_UNK_0                   = 2357, // GENERAL_WORLDSTATES_06
    WORLD_STATE_OPVP_EP_UNK_1                   = 2358, // GENERAL_WORLDSTATES_07
    WORLD_STATE_OPVP_EP_UNK_2                   = 2364, // GENERAL_WORLDSTATES_09
    WORLD_STATE_OPVP_EP_UNK_3                   = 2365, // GENERAL_WORLDSTATES_10
    // WORLD_STATE_OPVP_EP_UNK_4                = 2367, // GENERAL_WORLDSTATES_13 grey horde not in dbc! See: PlaguewoodTowerNH
    WORLD_STATE_OPVP_EP_UNK_5                   = 2368, // GENERAL_WORLDSTATES_11
    WORLD_STATE_OPVP_EP_UNK_6                   = 2369, // GENERAL_WORLDSTATES_12
    WORLD_STATE_OPVP_EP_UNK_7                   = 2376, // GENERAL_WORLDSTATES_04
    WORLD_STATE_OPVP_EP_UNK_8                   = 2377, // GENERAL_WORLDSTATES_05

    // Hellfire Peninsula Outdoor PvP
    WORLD_STATE_OPVP_HP_STADIUM_H               = 2470, // show the horde stadium icon
    WORLD_STATE_OPVP_HP_STADIUM_A               = 2471, // show the ally stadium icon
    WORLD_STATE_OPVP_HP_STADIUM_N               = 2472, // show the neutral stadium icon
    WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_DISPLAY = 2473, //: ally / horde slider display                                // show only in direct vicinity!
    WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_POS     = 2474, //: ally / horde slider percentage, 100 for ally, 0 for horde  // show only in direct vicinity!
    WORLD_STATE_OPVP_HP_UI_TOWER_SLIDER_N       = 2475, //: ally / horde slider grey area                              // show only in direct vicinity!
    WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_A        = 2476, // ally pvp objectives captured
    WORLD_STATE_OPVP_HP_UI_TOWER_COUNT_H        = 2478, // horde pvp objectives captured
    WORLD_STATE_OPVP_HP_OVERLOOK_A              = 2480, // show ally overlook icon
    WORLD_STATE_OPVP_HP_OVERLOOK_H              = 2481, // show the overlook arrow
    WORLD_STATE_OPVP_HP_OVERLOOK_N              = 2482, // show neutral overlook icon
    WORLD_STATE_OPVP_HP_BROKENHILL_A            = 2483, // show ally broken hill icon
    WORLD_STATE_OPVP_HP_BROKENHILL_H            = 2484, // show icon above broken hill
    WORLD_STATE_OPVP_HP_BROKENHILL_N            = 2485, // show neutral broken hill icon
    WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_H      = 2489, // add horde tower main gui icon      // maybe should be sent only on login?
    WORLD_STATE_OPVP_HP_UI_TOWER_DISPLAY_A      = 2490, // add ally tower main gui icon       // maybe should be sent only on login?

    // Zangarmarsh Outdoor PvP
    WORLD_STATE_OPVP_ZM_UI_TOWER_SLIDER_DISPLAY_W   = 2527,
    WORLD_STATE_OPVP_ZM_UI_TOWER_SLIDER_POS_W       = 2528,
    WORLD_STATE_OPVP_ZM_UI_TOWER_SLIDER_N_W         = 2529,
    WORLD_STATE_OPVP_ZM_UI_TOWER_SLIDER_DISPLAY_E   = 2533,
    WORLD_STATE_OPVP_ZM_UI_TOWER_SLIDER_POS_E       = 2534,
    WORLD_STATE_OPVP_ZM_UI_TOWER_SLIDER_N_E         = 2535,
    WORLD_STATE_OPVP_ZM_UI_TOWER_WEST_A             = 2555,
    WORLD_STATE_OPVP_ZM_UI_TOWER_WEST_H             = 2556,
    WORLD_STATE_OPVP_ZM_UI_TOWER_WEST_N             = 2557,
    WORLD_STATE_OPVP_ZM_UI_TOWER_EAST_A             = 2558,
    WORLD_STATE_OPVP_ZM_UI_TOWER_EAST_H             = 2559,
    WORLD_STATE_OPVP_ZM_UI_TOWER_EAST_N             = 2560,
    WORLD_STATE_OPVP_ZM_MAP_TOWER_WEST_A            = 2644,
    WORLD_STATE_OPVP_ZM_MAP_TOWER_WEST_H            = 2645,
    WORLD_STATE_OPVP_ZM_MAP_TOWER_WEST_N            = 2646,
    WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_N             = 2647,
    WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_A             = 2648,
    WORLD_STATE_OPVP_ZM_MAP_GRAVEYARD_H             = 2649, // Twin spire graveyard horde
    WORLD_STATE_OPVP_ZM_MAP_TOWER_EAST_A            = 2650,
    WORLD_STATE_OPVP_ZM_MAP_TOWER_EAST_H            = 2651,
    WORLD_STATE_OPVP_ZM_MAP_TOWER_EAST_N            = 2652,
    WORLD_STATE_OPVP_ZM_UNK                         = 2653,
    WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_READY     = 2655,
    WORLD_STATE_OPVP_ZM_MAP_ALLIANCE_FLAG_NOT_READY = 2656,
    WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_NOT_READY    = 2657,
    WORLD_STATE_OPVP_ZM_MAP_HORDE_FLAG_READY        = 2658,

    // Terokkar Forest Outdoor PvP
    WORLD_STATE_OPVP_TF_UI_LOCKED_DISPLAY_NEUTRAL           = 2508,
    WORLD_STATE_OPVP_TF_UI_LOCKED_TIME_HOURS                = 2509,
    WORLD_STATE_OPVP_TF_UI_LOCKED_TIME_MINUTES_SECOND_DIGIT = 2510,
    WORLD_STATE_OPVP_TF_UI_LOCKED_TIME_MINUTES_FIRST_DIGIT  = 2512,
    WORLD_STATE_OPVP_TF_UI_TOWERS_CONTROLLED_DISPLAY        = 2620,
    WORLD_STATE_OPVP_TF_UI_TOWER_COUNT_A                    = 2621,
    WORLD_STATE_OPVP_TF_UI_TOWER_COUNT_H                    = 2622,
    WORLD_STATE_OPVP_TF_UI_TOWER_SLIDER_DISPLAY             = 2623,
    WORLD_STATE_OPVP_TF_UI_TOWER_SLIDER_N                   = 2624,
    WORLD_STATE_OPVP_TF_UI_TOWER_SLIDER_POS                 = 2625,
    WORLD_STATE_OPVP_TF_TOWER_NUM_00                        = 2681, // NW Neutral
    WORLD_STATE_OPVP_TF_TOWER_NUM_01                        = 2682, // NW Horde
    WORLD_STATE_OPVP_TF_TOWER_NUM_02                        = 2683, // NW Alliance
    WORLD_STATE_OPVP_TF_TOWER_NUM_03                        = 2684, // N Alliance
    WORLD_STATE_OPVP_TF_TOWER_NUM_04                        = 2685, // N Horde
    WORLD_STATE_OPVP_TF_TOWER_NUM_05                        = 2686, // N Neutral
    WORLD_STATE_OPVP_TF_TOWER_NUM_15                        = 2687, // unk
    WORLD_STATE_OPVP_TF_TOWER_NUM_06                        = 2688, // NE Alliance
    WORLD_STATE_OPVP_TF_TOWER_NUM_07                        = 2689, // NE Horde
    WORLD_STATE_OPVP_TF_TOWER_NUM_08                        = 2690, // NE Neutral
    WORLD_STATE_OPVP_TF_TOWER_NUM_09                        = 2691, // S Alliance
    WORLD_STATE_OPVP_TF_TOWER_NUM_10                        = 2692, // S Horde
    WORLD_STATE_OPVP_TF_TOWER_NUM_11                        = 2693, // S Neutral
    WORLD_STATE_OPVP_TF_TOWER_NUM_12                        = 2694, // SE Alliance
    WORLD_STATE_OPVP_TF_TOWER_NUM_13                        = 2695, // SE Horde
    WORLD_STATE_OPVP_TF_TOWER_NUM_14                        = 2696, // SE Neutral
    WORLD_STATE_OPVP_TF_UI_LOCKED_DISPLAY_ALLIANCE          = 2767,
    WORLD_STATE_OPVP_TF_UI_LOCKED_DISPLAY_HORDE             = 2768,

    // Halaa, Nagrand Outdoor PvP
    WORLD_STATE_OPVP_NA_UI_GUARDS_LEFT          = 2491,
    WORLD_STATE_OPVP_NA_UI_GUARDS_MAX           = 2493,
    WORLD_STATE_OPVP_NA_UI_TOWER_SLIDER_POS     = 2494,
    WORLD_STATE_OPVP_NA_UI_TOWER_SLIDER_DISPLAY = 2495, // OUTLAND_01 "Progress: %2494w"
    WORLD_STATE_OPVP_NA_UI_SLIDER_N             = 2497,
    WORLD_STATE_OPVP_NA_UI_ALLIANCE_GUARDS_SHOW = 2502,
    WORLD_STATE_OPVP_NA_UI_HORDE_GUARDS_SHOW    = 2503,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_EAST_NEU_A   = 2659,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_EAST_H       = 2660,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_EAST_A       = 2661,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_NORTH_NEU_A  = 2662,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_NORTH_H      = 2663,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_NORTH_A      = 2664,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_WEST_H       = 2665,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_WEST_A       = 2666,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_WEST_NEU_A   = 2667,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_SOUTH_H      = 2668,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_SOUTH_A      = 2669,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_SOUTH_NEU_A  = 2670,
    WORLD_STATE_OPVP_NA_MAP_HALAA_NEUTRAL       = 2671,
    WORLD_STATE_OPVP_NA_MAP_HALAA_HORDE         = 2672,
    WORLD_STATE_OPVP_NA_MAP_HALAA_ALLIANCE      = 2673,
    WORLD_STATE_OPVP_NA_MAP_HALAA_NEU_A         = 2676,
    WORLD_STATE_OPVP_NA_MAP_HALAA_NEU_H         = 2677,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_SOUTH_NEU_H  = 2760,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_WEST_NEU_H   = 2761,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_NORTH_NEU_H  = 2762,
    WORLD_STATE_OPVP_NA_MAP_WYVERN_EAST_NEU_H   = 2763,

    // Grizzly Hills Outdoor PvP
    WORLD_STATE_OPVP_GH_UI_SLIDER_DISPLAY = 3466,
    WORLD_STATE_OPVP_GH_UI_SLIDER_POS     = 3467,
    WORLD_STATE_OPVP_GH_UI_SLIDER_N       = 3468,

    // Ahn'Qiraj
    WORLD_STATE_AHNQIRAJ_SANDWORM_N  = 2322,
    WORLD_STATE_AHNQIRAJ_SANDWORM_S  = 2323,
    WORLD_STATE_AHNQIRAJ_SANDWORM_SW = 2324,
    WORLD_STATE_AHNQIRAJ_SANDWORM_E  = 2325,

    // The Battle for Light's Hope Chapel - Scarlet Enclave
    WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_DEFENDERS_COUNT    = 3590,
    WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SCOURGE_COUNT      = 3591,
    WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_SOLDIERS_ENABLE    = 3592,
    WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_ENABLE   = 3603,
    WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_COUNTDOWN_TIME     = 3604,
    WORLD_STATE_BATTLE_FOR_LIGHTS_HOPE_EVENT_BEGIN_ENABLE = 3605,

    // The Battle for the Undercity
    WORLD_STATE_BATTLE_FOR_UNDERCITY_MANHUNT_COUNTDOWN_A   = 3958,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_SEWERS_FIGHT_A        = 3962,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_FAIL_A                = 3963,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_SEWERS_DONE_A         = 3964,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_MANHUNT_STARTS_A      = 3966,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_APOTHECARIUM_DONE_A   = 3971,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_APOTHECARIUM_FIGHT_A  = 3972,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_START_H               = 3875,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_COUNTDOWN_H           = 3876,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_FAIL_H                = 3878,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_COURTYARD_FIGHT_H     = 3885,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_COURTYARD_DONE_H      = 3886,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_INNER_SANCTUM_FIGHT_H = 3887,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_INNER_SANCTUM_DONE_H  = 3888,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_ROYAL_QUARTER_FIGHT_H = 3889,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_ROYAL_QUARTER_DONE_H  = 3890,
    WORLD_STATE_BATTLE_FOR_UNDERCITY_APOTHECARIUM_FIGHT_H  = 3891, // unused
    WORLD_STATE_BATTLE_FOR_UNDERCITY_APOTHECARIUM_DONE_H   = 3892, // unused

    // The Ruby Sanctum
    WORLD_STATE_RUBY_SANCTUM_CORPOREALITY_MATERIAL = 5049,
    WORLD_STATE_RUBY_SANCTUM_CORPOREALITY_TWILIGHT = 5050,
    WORLD_STATE_RUBY_SANCTUM_CORPOREALITY_TOGGLE   = 5051,

    // Icecrown Citadel
    WORLD_STATE_ICECROWN_CITADEL_SHOW_TIMER         = 4903, // Blood Quickening weekly
    WORLD_STATE_ICECROWN_CITADEL_EXECUTION_TIME     = 4904,
    WORLD_STATE_ICECROWN_CITADEL_SHOW_ATTEMPTS      = 4940,
    WORLD_STATE_ICECROWN_CITADEL_ATTEMPTS_REMAINING = 4941,
    WORLD_STATE_ICECROWN_CITADEL_ATTEMPTS_MAX       = 4942,

    // The Culling of Stratholme
    WORLD_STATE_CULLING_OF_STRATHOLME_SHOW_CRATES        = 3479,
    WORLD_STATE_CULLING_OF_STRATHOLME_CRATES_REVEALED    = 3480,
    WORLD_STATE_CULLING_OF_STRATHOLME_WAVE_COUNT         = 3504,
    WORLD_STATE_CULLING_OF_STRATHOLME_TIME_GUARDIAN      = 3931,
    WORLD_STATE_CULLING_OF_STRATHOLME_TIME_GUARDIAN_SHOW = 3932,

    // The Oculus
    WORLD_STATE_OCULUS_CENTRIFUGE_CONSTRUCT_AMOUNT = 3486,
    WORLD_STATE_OCULUS_CENTRIFUGE_CONSTRUCT_SHOW   = 3524,

    // Ulduar
    WORLD_STATE_ULDUAR_ALGALON_DESPAWN_TIMER = 4131,
    WORLD_STATE_ULDUAR_ALGALON_TIMER_ENABLED = 4132,

    // The Violet Hold
    WORLD_STATE_VIOLET_HOLD_WAVE_COUNT   = 3810,
    WORLD_STATE_VIOLET_HOLD_PRISON_STATE = 3815,
    WORLD_STATE_VIOLET_HOLD_SHOW         = 3816,

    // Halls of Reflection
    WORLD_STATE_HALLS_OF_REFLECTION_WAVE_COUNT    = 4882,
    WORLD_STATE_HALLS_OF_REFLECTION_WAVES_ENABLED = 4884,

    // Zul'Aman
    WORLD_STATE_ZUL_AMAN_SHOW_TIMER        = 3104,
    WORLD_STATE_ZUL_AMAN_TIME_TO_SACRIFICE = 3106,

    // The Black Morass
    WORLD_STATE_BLACK_MORASS_SHIELD = 2540,
    WORLD_STATE_BLACK_MORASS        = 2541,
    WORLD_STATE_BLACK_MORASS_RIFT   = 2784,

    // Battle for Mount Hyjal
    WORLD_STATE_HYJAL_ENEMY       = 2453,
    WORLD_STATE_HYJAL_ENEMY_COUNT = 2454,
    WORLD_STATE_HYJAL_WAVES       = 2842,

    // Escape From Durnholde Keep
    WORLD_STATE_OLD_HILLSBRAD_BARRELS_PLANTED = 2436,

    // Trial of the Crusader
    WORLD_STATE_TRIAL_OF_THE_CRUSADER_UI_COUNT = 4389,
    WORLD_STATE_TRIAL_OF_THE_CRUSADER_UI_SHOW  = 4390,

    // Stranglethorn Fishing Extravaganza (Are these custom IDs?)
    WORLD_STATE_STRANGLETHORN_VALE_FISHING_PREV_WIN_TIME          = 197,
    WORLD_STATE_STRANGLETHORN_VALE_FISHING_HAS_WINNER             = 198,
    WORLD_STATE_STRANGLETHORN_VALE_FISHING_ANNOUNCE_EVENT_BEGIN   = 199,
    WORLD_STATE_STRANGLETHORN_VALE_FISHING_ANNOUNCE_POOLS_DESPAWN = 200,

    // Custom
    WORLD_STATE_CUSTOM_ARENA_DISTRIBUTION_TIME                 = 20001, // Next arena distribution time
    WORLD_STATE_CUSTOM_WEEKLY_QUEST_RESET_TIME                 = 20002, // Next weekly reset time
    WORLD_STATE_CUSTOM_BG_DAILY_RESET_TIME                     = 20003, // Next daily BG reset time
    WORLD_STATE_CUSTOM_CLEANING_FLAGS                          = 20004, // Cleaning Flags
    WORLD_STATE_CUSTOM_DAILY_QUEST_RESET_TIME                  = 20005, // Next daily reset time
    WORLD_STATE_CUSTOM_GUILD_DAILY_RESET_TIME                  = 20006, // Next guild cap reset time
    WORLD_STATE_CUSTOM_MONTHLY_QUEST_RESET_TIME                = 20007, // Next monthly reset time
    WORLD_STATE_CUSTOM_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME = 20008, // Next daily calendar deletions of old events time
};

#endif
