/*
 * This file is part of the AzerothCore Project. See AUTHORS file for Copyright information
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef WORLD_STATE_DEFINES_H
#define WORLD_STATE_DEFINES_H

enum WorldStateIDs
{
    // Scourge Invasion
    WORLD_STATE_SCOURGE_INVASION_VICTORIES = 2219,

    // Active Invasion Indicators
    WORLD_STATE_SCOURGE_INVASION_WINTERSPRING = 2259,
    WORLD_STATE_SCOURGE_INVASION_AZSHARA = 2260,
    WORLD_STATE_SCOURGE_INVASION_BLASTED_LANDS = 2261,
    WORLD_STATE_SCOURGE_INVASION_BURNING_STEPPES = 2262,
    WORLD_STATE_SCOURGE_INVASION_TANARIS = 2263,
    WORLD_STATE_SCOURGE_INVASION_EASTERN_PLAGUELANDS = 2264,

    // Active Necropoli
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_AZSHARA = 2279,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_BLASTED_LANDS = 2280,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_BURNING_STEPPES = 2281,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_EASTERN_PLAGUELANDS = 2282,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_TANARIS = 2283,
    WORLD_STATE_SCOURGE_INVASION_NECROPOLIS_WINTERSPRING = 2284,

    // Arena
    WORLD_STATE_ARENA_SEASON_PROGRESS = 3191,
    WORLD_STATE_ARENA_SEASON_ID = 3901,

    // Sun's Reach Reclamation
    WORLD_STATE_QUEL_DANAS_MUSIC = 3426,
    WORLD_STATE_QUEL_DANAS_HARBOR = 3238,
    WORLD_STATE_QUEL_DANAS_ALCHEMY_LAB = 3223,
    WORLD_STATE_QUEL_DANAS_ARMORY = 3233,
    WORLD_STATE_QUEL_DANAS_SANCTUM = 3244,
    WORLD_STATE_QUEL_DANAS_PORTAL = 3269,
    WORLD_STATE_QUEL_DANAS_ANVIL = 3228,
    WORLD_STATE_QUEL_DANAS_MONUMENT = 3275,

    // Sunwell Gate
    WORLD_STATE_AGAMATH_THE_FIRST_GATE_HEALTH = 3253, // guessed, potentially wrong
    WORLD_STATE_ROHENDOR_THE_SECOND_GATE_HEALTH = 3255,
    WORLD_STATE_ARCHONISUS_THE_FINAL_GATE_HEALTH = 3257,

    // Wintergrasp
    WORLD_STATE_BATTLEFIELD_WG_VEHICLE_H = 3490,
    WORLD_STATE_BATTLEFIELD_WG_MAX_VEHICLE_H = 3491,
    WORLD_STATE_BATTLEFIELD_WG_VEHICLE_A = 3680,
    WORLD_STATE_BATTLEFIELD_WG_MAX_VEHICLE_A = 3681,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_K_W = 3698,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_K_E = 3699,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_NW = 3700,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_NE = 3701,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_SW = 3702,
    WORLD_STATE_BATTLEFIELD_WG_WORKSHOP_SE = 3703,
    WORLD_STATE_BATTLEFIELD_WG_SHOW_WORLDSTATE = 3710,
    WORLD_STATE_BATTLEFIELD_WG_CLOCK = 3781,
    WORLD_STATE_BATTLEFIELD_WG_ACTIVE = 3801,
    WORLD_STATE_BATTLEFIELD_WG_DEFENDER = 3802,
    WORLD_STATE_BATTLEFIELD_WG_ATTACKER = 3803,
    WORLD_STATE_BATTLEFIELD_WG_CONTROL = 3804, // Shows on the map who controls WG
    WORLD_STATE_BATTLEFIELD_WG_HORDE_KEEP_CAPTURED = 4022,
    WORLD_STATE_BATTLEFIELD_WG_ALLIANCE_KEEP_CAPTURED = 4023,
    WORLD_STATE_BATTLEFIELD_WG_HORDE_KEEP_DEFENDED = 4024,
    WORLD_STATE_BATTLEFIELD_WG_ALLIANCE_KEEP_DEFENDED = 4025,
    WORLD_STATE_BATTLEFIELD_WG_CLOCK_TEXTS = 4354,
    WORLD_STATE_BATTLEFIELD_WG_ICON_ACTIVE = 4375, // Activates "ice" icon

    // Alterac Valley
    WORLD_STATE_BATTLEGROUND_AV_STORMPIKE_LIEUTENANTS = 950,
    WORLD_STATE_BATTLEGROUND_AV_STORMPIKE_COMMANDERS = 962,
    WORLD_STATE_BATTLEGROUND_AV_UNK_0 = 964,
    WORLD_STATE_BATTLEGROUND_AV_UNK_1 = 966,
    WORLD_STATE_BATTLEGROUND_AV_STONEHEART_H_C = 1301,
    WORLD_STATE_BATTLEGROUND_AV_STONEHEART_A_C = 1302,
    WORLD_STATE_BATTLEGROUND_AV_STONEHEART_H_A = 1303,
    WORLD_STATE_BATTLEGROUND_AV_STONEHEART_A_A = 1304,
    WORLD_STATE_BATTLEGROUND_AV_AID_A_C = 1325,
    WORLD_STATE_BATTLEGROUND_AV_AID_A_A = 1326,
    WORLD_STATE_BATTLEGROUND_AV_AID_H_C = 1327,
    WORLD_STATE_BATTLEGROUND_AV_AID_H_A = 1328,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFHUT_A_C = 1329,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFHUT_H_C = 1330,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFHUT_A_A = 1331,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFHUT_H_A = 1332,
    WORLD_STATE_BATTLEGROUND_AV_PIKEGRAVE_A_C = 1333,
    WORLD_STATE_BATTLEGROUND_AV_PIKEGRAVE_H_C = 1334,
    WORLD_STATE_BATTLEGROUND_AV_PIKEGRAVE_A_A = 1335,
    WORLD_STATE_BATTLEGROUND_AV_PIKEGRAVE_H_A = 1336,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLF_A_C = 1337,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLF_H_C = 1338,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLF_A_A = 1339,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLF_H_A = 1340,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_A_C = 1341,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_H_C = 1342,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_A_A = 1343,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_H_A = 1344,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_A_C = 1346,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_H_C = 1347,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_A_A = 1348,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_H_A = 1349,
    WORLD_STATE_BATTLEGROUND_AV_S_MINE_A = 1355,
    WORLD_STATE_BATTLEGROUND_AV_S_MINE_H = 1356,
    WORLD_STATE_BATTLEGROUND_AV_S_MINE_N = 1357,
    WORLD_STATE_BATTLEGROUND_AV_N_MINE_A = 1358,
    WORLD_STATE_BATTLEGROUND_AV_N_MINE_H = 1359,
    WORLD_STATE_BATTLEGROUND_AV_N_MINE_N = 1360,
    WORLD_STATE_BATTLEGROUND_AV_DUNS_CONTROLLED = 1361,
    WORLD_STATE_BATTLEGROUND_AV_DUNN_CONTROLLED = 1362,
    WORLD_STATE_BATTLEGROUND_AV_ICEWING_CONTROLLED = 1363,
    WORLD_STATE_BATTLEGROUND_AV_STONEH_CONTROLLED = 1364,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFW_DESTROYED = 1365,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFE_DESTROYED = 1366,
    WORLD_STATE_BATTLEGROUND_AV_TOWERPOINT_DESTROYED = 1367,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_DESTROYED = 1368,
    WORLD_STATE_BATTLEGROUND_AV_UNK_2 = 1369,
    WORLD_STATE_BATTLEGROUND_AV_DUNS_DESTROYED = 1370,
    WORLD_STATE_BATTLEGROUND_AV_DUNN_DESTROYED = 1371,
    WORLD_STATE_BATTLEGROUND_AV_ICEWING_DESTROYED = 1372,
    WORLD_STATE_BATTLEGROUND_AV_STONEH_DESTROYED = 1373,
    WORLD_STATE_BATTLEGROUND_AV_DUNN_UNUSED = 1374, // Unused
    WORLD_STATE_BATTLEGROUND_AV_DUNS_UNUSED = 1375, // Unused
    WORLD_STATE_BATTLEGROUND_AV_ICEWING_UNUSED = 1376, // Unused
    WORLD_STATE_BATTLEGROUND_AV_STONEH_UNUSED = 1377, // Unused
    WORLD_STATE_BATTLEGROUND_AV_DUNS_ASSAULTED = 1378,
    WORLD_STATE_BATTLEGROUND_AV_DUNN_ASSAULTED = 1379,
    WORLD_STATE_BATTLEGROUND_AV_ICEWING_ASSAULTED = 1380,
    WORLD_STATE_BATTLEGROUND_AV_STONEH_ASSAULTED = 1381,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFW_CONTROLLED = 1382,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFE_CONTROLLED = 1383,
    WORLD_STATE_BATTLEGROUND_AV_TOWERPOINT_CONTROLLED = 1384,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_CONTROLLED = 1385,
    WORLD_STATE_BATTLEGROUND_AV_UNK_3 = 1386,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFW_ASSAULTED = 1387,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFE_ASSAULTED = 1388,
    WORLD_STATE_BATTLEGROUND_AV_TOWERPOINT_ASSAULTED = 1389,
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_ASSAULTED = 1390,
    WORLD_STATE_BATTLEGROUND_AV_UNK_4 = 1391,
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFW_UNUSED = 1392, // Unused
    WORLD_STATE_BATTLEGROUND_AV_FROSTWOLFE_UNUSED = 1393, // Unused
    WORLD_STATE_BATTLEGROUND_AV_TOWERPOINT_UNUSED = 1394, // Unused
    WORLD_STATE_BATTLEGROUND_AV_ICEBLOOD_UNUSED = 1395, // Unused
    WORLD_STATE_BATTLEGROUND_AV_UNK_5 = 1396,
    WORLD_STATE_BATTLEGROUND_AV_SNOWFALL_N = 1966,
    WORLD_STATE_BATTLEGROUND_AV_ALLIANCE_SCORE = 3127,
    WORLD_STATE_BATTLEGROUND_AV_HORDE_SCORE = 3128,
    WORLD_STATE_BATTLEGROUND_AV_SHOW_HORDE_SCORE = 3133,
    WORLD_STATE_BATTLEGROUND_AV_SHOW_ALLIANCE_SCORE = 3134,

    // Warsong Gulch
    WORLD_STATE_BATTLEGROUND_WS_UNK_0 = 1545, // set to 1 on alliance flag pickup...
    WORLD_STATE_BATTLEGROUND_WS_UNK_1 = 1546, // set to 1 on horde flag pickup, after drop it's -1
    WORLD_STATE_BATTLEGROUND_WS_UNK_2 = 1547,
    WORLD_STATE_BATTLEGROUND_WS_FLAG_CAPTURES_ALLIANCE = 1581,
    WORLD_STATE_BATTLEGROUND_WS_FLAG_CAPTURES_HORDE = 1582,
    WORLD_STATE_BATTLEGROUND_WS_FLAG_CAPTURES_MAX = 1601, // unk
    WORLD_STATE_BATTLEGROUND_WS_FLAG_STATE_HORDE = 2338, // (0 - hide, 1 - flag ok, 2 - flag picked up (flashing), 3 - flag picked up (not flashing)
    WORLD_STATE_BATTLEGROUND_WS_FLAG_STATE_ALLIANCE = 2339, // (0 - hide, 1 - flag ok, 2 - flag picked up (flashing), 3 - flag picked up (not flashing)
    WORLD_STATE_BATTLEGROUND_WS_STATE_TIMER_ACTIVE = 4247,
    WORLD_STATE_BATTLEGROUND_WS_STATE_TIMER = 4248,
};

#endif
